export const GET_ADDRESS_PIC_LOADING = 'GET_ADDRESS_MULTIPLE_PIC_LOADING';
export const GET_ADDRESS_PIC_SUCCESS = 'GET_ADDRESS_MULTIPLE_PIC_SUCCESS';
export const GET_ADDRESS_PIC_ERROR = 'GET_ADDRESS_MULTIPLE_PIC_ERROR';

export const UPLOAD_PHYSICAL_ADDRESS_LOADING = 'UPLOAD_ADDRESS_URL_LOADING';
export const UPLOAD_PHYSICAL_ADDRESS_SUCCESS = 'UPLOAD_ADDRESS_URL_SUCCESS';
export const UPLOAD_PHYSICAL_ADDRESS_ERROR = 'UPLOAD_ADDRESS_URL_ERROR';

export const DELETE_PHYSICAL_ADDRESS_LOADING = 'DELETE_MULTIPLE_ADDRESS_URL_LOADING';
export const DELETE_PHYSICAL_ADDRESS_SUCCESS = 'DELETE_MULTIPLE_ADDRESS_URL_SUCCESS';
export const DELETE_PHYSICAL_ADDRESS_ERROR = 'DELETE_MULTIPLE_ADDRESS_URL_ERROR';