export const INIT_STATE = 'INIT_CONTACT_STATE';
export const RESET_ERROR = 'RESET_ORG_CONTACT_ERROR';

export const GET_DATA_LIST_LOADING = 'GET_CONTACT_LIST_LOADING';
export const GET_DATA_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_CONTACT_LIST_ERROR';

export const POST_DATA_LOADING = 'POST_CONTACT_LOADING';
export const POST_DATA_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_DATA_ERROR = 'POST_CONTACT_ERROR';

export const PUT_DATA_LOADING = 'PUT_CONTACT_LOADING';
export const PUT_DATA_SUCCESS = 'PUT_CONTACT_SUCCESS';
export const PUT_DATA_ERROR = 'PUT_CONTACT_ERROR';

export const DELETE_DATA_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_DATA_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_CONTACT_ERROR';
