export const INIT_STATE = 'ORG_ATTEND_CONFIG_INIT_STATE';
export const ORG_CONFIG_LOADING = 'ORG_ATTEND_CONFIG_LOADING';
export const ORG_CONFIG_SUCCESS = 'ORG_ATTEND_CONFIG_SUCCESS';
export const ORG_CONFIG_ERROR = 'ORG_ATTEND_CONFIG_ERROR';
