export const GET_SELECTED_SERVICE_DATA_LOADING = 'GET_SELECTED_SERVICE_DATA_LOADING';
export const GET_SELECTED_SERVICE_DATA_SUCCESS = 'GET_SELECTED_SERVICE_DATA_SUCCESS';
export const GET_SELECTED_SERVICE_DATA_ERROR = 'GET_SELECTED_SERVICE_DATA_ERROR';

export const POST_STATUS_DATA_LOADING = "POST_STATUS_DATA_LOADING";
export const POST_STATUS_DATA_SUCCESS = "POST_STATUS_DATA_SUCCESS";
export const POST_STATUS_DATA_ERROR = "POST_STATUS_DATA_ERROR";

export const PUT_CHECK_LEVEL_DATA_LOADING = "PUT_CHECK_LEVEL_DATA_LOADING";
export const PUT_CHECK_LEVEL_DATA_SUCCESS = "PUT_CHECK_LEVEL_DATA_SUCCESS";
export const PUT_CHECK_LEVEL_DATA_ERROR = "PUT_CHECK_LEVEL_DATA_ERROR";

export const PUT_SECTION_LEVEL_DATA_LOADING = "PUT_SECTION_LEVEL_DATA_LOADING";
export const PUT_SECTION_LEVEL_DATA_SUCCESS = "PUT_SECTION_LEVEL_DATA_SUCCESS";
export const PUT_SECTION_LEVEL_DATA_ERROR = "PUT_SECTION_LEVEL_DATA_ERROR";

export const PUT_PROFILE_LEVEL_DATA_LOADING = "PUT_PROFILE_LEVEL_DATA_LOADING";
export const PUT_PROFILE_LEVEL_DATA_SUCCESS = "PUT_PROFILE_LEVEL_DATA_SUCCESS";
export const PUT_PROFILE_LEVEL_DATA_ERROR = "PUT_PROFILE_LEVEL_DATA_ERROR";

export const GET_STATUS_DATA_LOADING = 'GET_STATUS_DATA_LOADING';
export const GET_STATUS_DATA_SUCCESS = 'GET_STATUS_DATA_SUCCESS';
export const GET_STATUS_DATA_ERROR = 'GET_STATUS_DATA_ERROR';

export const GET_INIT_STATE = 'GET_INIT_STATE';

export const RESET_ERROR = "RESET_ERROR";

export const SET_STATUSMGMT_TOPNAV = 'SET_STATUSMGMT_TOPNAV';