export const INIT_STATE = 'INIT_BGV_CONFIG_STATE';

export const SET_BGV_CONFIG_STATUS = 'SET_BGV_CONFIG_STATUS';

export const GET_ALL_SERVICES_DATA_LOADING = 'GET_ALL_SERVICES_DATA_LOADING';
export const GET_ALL_SERVICES_DATA_SUCCESS = 'GET_ALL_SERVICES_DATA_SUCCESS';
export const GET_ALL_SERVICES_DATA_ERROR = 'GET_ALL_SERVICES_DATA_ERROR';