export const GET_INIT_STATE = 'GET_INIT_STATE'

export const POST_SERVICE_DATA_LOADING = 'POST_SERVICE_DATA_LOADING';
export const POST_SERVICE_DATA_SUCCESS = 'POST_SERVICE_DATA_SUCCESS';
export const POST_SERVICE_DATA_ERROR = 'POST_SERVICE_DATA_ERROR';

export const PUT_SERVICE_DATA_LOADING = 'PUT_SERVICE_DATA_LOADING';
export const PUT_SERVICE_DATA_SUCCESS = 'PUT_SERVICE_DATA_SUCCESS';
export const PUT_SERVICE_DATA_ERROR = 'PUT_SERVICE_DATA_ERROR';

export const GET_SELECTED_SERVICE_DATA_LOADING = 'GET_SELECTED_SERVICE_DATA_LOADING';
export const GET_SELECTED_SERVICE_DATA_SUCCESS = 'GET_SELECTED_SERVICE_DATA_SUCCESS';
export const GET_SELECTED_SERVICE_DATA_ERROR = 'GET_SELECTED_SERVICE_DATA_ERROR';

export const GET_ALL_SERVICES_DATA_LOADING = 'GET_ALL_SERVICES_DATA_LOADING';
export const GET_ALL_SERVICES_DATA_SUCCESS = 'GET_ALL_SERVICES_DATA_SUCCESS';
export const GET_ALL_SERVICES_DATA_ERROR = 'GET_ALL_SERVICES_DATA_ERROR';

export const GET_AGENCY_LIST_LOADING = 'GET_AGENCY_LIST_LOADING';
export const GET_AGENCY_LIST_SUCCESS = 'GET_AGENCY_LIST_SUCCESS';
export const GET_AGENCY_LIST_ERROR = 'GET_AGENCY_LIST_ERROR';