export const GET_ORG_DATA_LOADING = 'ATTEND_DASHBOARD_GET_ORG_DATA_LOADING';
export const GET_ORG_DATA_SUCCESS = 'ATTEND_DASHBOARD_GET_ORG_DATA_SUCCESS';
export const GET_ORG_DATA_ERROR = 'ATTEND_DASHBOARD_GET_ORG_DATA_ERROR';
