export const INIT_STATE = 'INIT_ADDRESS_VERIFICATION_STATE';

export const RESET_ERROR = 'RESET_ADDRESS_VERIFICATION_ERROR';

export const SEARCH_AGENCY_CANDIDATE_LOADING = 'SEARCH_AGENCY_CANDIDATE_LOADING';
export const SEARCH_AGENCY_CANDIDATE_SUCCESS = 'SEARCH_AGENCY_CANDIDATE_SUCCESS';
export const SEARCH_AGENCY_CANDIDATE_ERROR = 'SEARCH_AGENCY_CANDIDATE_ERROR';

export const GET_AGENCY_LIST_LOADING = 'GET_AGENCY_LIST_LOADING';
export const GET_AGENCY_LIST_SUCCESS = 'GET_AGENCY_LIST_SUCCESS';
export const GET_AGENCY_LIST_ERROR = 'GET_AGENCY_LIST_ERROR';

export const GET_TASKS_COUNT_LOADING = 'GET_TASKS_COUNT_LOADING';
export const GET_TASKS_COUNT_SUCCESS = 'GET_TASKS_COUNT_SUCCESS';
export const GET_TASKS_COUNT_ERROR = 'GET_TASKS_COUNT_ERROR';

export const GET_AGENCY_TASKS_LOADING = 'GET_AGENCY_TASKS_LOADING';
export const GET_AGENCY_TASKS_SUCCESS = 'GET_AGENCY_TASKS_SUCCESS';
export const GET_AGENCY_TASKS_ERROR = 'GET_AGENCY_TASKS_ERROR';

export const GET_STATIC_DATA_LOADING = 'GET_STATIC_DATA_LOADING';
export const GET_STATIC_DATA_SUCCESS = 'GET_STATIC_DATA_SUCCESS';
export const GET_STATIC_DATA_ERROR = 'GET_STATIC_DATA_ERROR';

export const GET_DISTRICT_STATIC_DATA_LOADING = 'GET_DISTRICT_STATIC_DATA_LOADING';
export const GET_DISTRICT_STATIC_DATA_SUCCESS = 'GET_DISTRICT_STATIC_DATA_SUCCESS';
export const GET_DISTRICT_STATIC_DATA_ERROR = 'GET_DISTRICT_STATIC_DATA_ERROR';

export const GET_CITY_STATIC_DATA_LOADING = 'GET_CITY_STATIC_DATA_LOADING';
export const GET_CITY_STATIC_DATA_SUCCESS = 'GET_CITY_STATIC_DATA_SUCCESS';
export const GET_CITY_STATIC_DATA_ERROR = 'GET_CITY_STATIC_DATA_ERROR';

export const GET_PINCODE_STATIC_DATA_LOADING = 'GET_PINCODE_STATIC_DATA_LOADING';
export const GET_PINCODE_STATIC_DATA_SUCCESS = 'GET_PINCODE_STATIC_DATA_SUCCESS';
export const GET_PINCODE_STATIC_DATA_ERROR = 'GET_PINCODE_STATIC_DATA_ERROR';

export const GET_CLIENT_STATIC_DATA_LOADING = 'GET_CLIENT_STATIC_DATA_LOADING';
export const GET_CLIENT_STATIC_DATA_SUCCESS = 'GET_CLIENT_STATIC_DATA_SUCCESS';
export const GET_CLIENT_STATIC_DATA_ERROR = 'GET_CLIENT_STATIC_DATA_ERROR';

export const GET_FILTER_COUNT_LOADING = 'GET_FILTER_COUNT_LOADING';
export const GET_FILTER_COUNT_SUCCESS = 'GET_FILTER_COUNT_SUCCESS';
export const GET_FILTER_COUNT_ERROR = 'GET_FILTER_COUNT_ERROR';

export const POST_REASSIGN_LOADING = 'POST_REASSIGN_LOADING';
export const POST_REASSIGN_SUCCESS = 'POST_REASSIGN_SUCCESS';
export const POST_REASSIGN_ERROR = 'POST_REASSIGN_ERROR';