export const INIT_CLIENT_TAGS_STATE = 'INIT_CLIENT_TAGS_STATE';

export const GET_ORG_NAME_LOADING = 'GET_ORG_NAME_LOADING';
export const GET_ORG_NAME_SUCCESS = 'GET_ORG_NAME_SUCCESS';
export const GET_ORG_NAME_ERROR = 'GET_ORG_NAME_ERROR';

export const GET_CLIENT_DATA_LOADING = 'GET_CLIENT_DATA_LOADING';
export const GET_CLIENT_DATA_SUCCESS = 'GET_CLIENT_DATA_SUCCESS';
export const GET_CLIENT_DATA_ERROR = 'GET_CLIENT_DATA_ERROR';

export const GET_CLIENT_TAGS_COUNT_LOADING = 'GET_CLIENT_TAGS_COUNT_LOADING';
export const GET_CLIENT_TAGS_COUNT_SUCCESS = 'GET_CLIENT_TAGS_COUNT_SUCCESS';
export const GET_CLIENT_TAGS_COUNT_ERROR = 'GET_CLIENT_TAGS_COUNT_ERROR';

export const GET_CLIENT_TAGS_LOADING = 'GET_CLIENT_TAGS_LOADING';
export const GET_CLIENT_TAGS_SUCCESS = 'GET_CLIENT_TAGS_SUCCESS';
export const GET_CLIENT_TAGS_ERROR = 'GET_CLIENT_TAGS_ERROR';

export const POST_SELECTED_FILTERS_TAG_DETAILS_LOADING = 'POST_SELECTED_FILTERS_TAG_DETAILS_LOADING';
export const POST_SELECTED_FILTERS_TAG_DETAILS_SUCCESS = 'POST_SELECTED_FILTERS_TAG_DETAILS_SUCCESS';
export const POST_SELECTED_FILTERS_TAG_DETAILS_ERROR = 'POST_SELECTED_FILTERS_TAG_DETAILS_ERROR';

export const POST_SELECTED_FILTERS_TAG_COUNT_LOADING = 'POST_SELECTED_FILTERS_TAG_COUNT_LOADING';
export const POST_SELECTED_FILTERS_TAG_COUNT_SUCCESS = 'POST_SELECTED_FILTERS_TAG_COUNT_SUCCESS';
export const POST_SELECTED_FILTERS_TAG_COUNT_ERROR = 'POST_SELECTED_FILTERS_TAG_COUNT_ERROR';
