export const INIT_STATE = 'INIT_TIMELINE_STATE';

export const GET_USER_DETAILS_LOADING = 'GET_TIMELINE_USER_DETAILS_LOADING';
export const GET_USER_DETAILS_SUCCESS = 'GET_TIMELINE_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_TIMELINE_USER_DETAILS_ERROR';

export const TIMELINE_DATA_LOADING = 'GET_TIMELINE_DATA_LOADING';
export const TIMELINE_DATA_SUCCESS = 'GET_TIMELINE_DATA_SUCCESS';
export const TIMELINE_DATA_ERROR = 'GET_TIMELINE_DATA_ERROR';

export const GET_TAG_NAME_LOADING = 'GET_TIMELINE_TAG_NAME_LOADING';
export const GET_TAG_NAME_SUCCESS = 'GET_TIMELINE_TAG_NAME_SUCCESS';
export const GET_TAG_NAME_ERROR = 'GET_TIMELINE_TAG_NAME_ERROR';

export const TIMELINE_FILE_DOWNLOAD_LOADING = 'GET_TIMELINE_FILE_DOWNLOAD_LOADING';
export const TIMELINE_FILE_DOWNLOAD_SUCCESS = 'GET_TIMELINE_FILE_DOWNLOAD_SUCCESS';
export const TIMELINE_FILE_DOWNLOAD_ERROR = 'GET_TIMELINE_FILE_DOWNLOAD_ERROR';