export const SET_ID_DATA='SET_ID_DATA';
export const GET_INIT_STATE='GET_INIT_STATE';

export const ENTITY_CHECK_LOADING = 'ENTITY_CHECK_LOADING';
export const ENTITY_CHECK_SUCCESS = 'ENTITY_CHECK_SUCCESS';
export const ENTITY_CHECK_ERROR = 'ENTITY_CHECK_ERROR';


export const GET_TAG_LOADING = 'GET_TAG_LOADING';
export const GET_TAG_SUCCESS = 'GET_TAG_SUCCESS';
export const GET_TAG_ERROR = 'GET_TAG_ERROR';

export const GET_DATA_LOADING = 'GET_DETAILS_LOADING';
export const GET_DATA_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DATA_ERROR = 'GET_DETAILS_ERROR';

export const DOWNLOAD_EXCEL_TEMPLATE_LOADING = 'DOWNLOAD_EXCEL_TEMPLATE_LOADING';
export const DOWNLOAD_EXCEL_TEMPLATE_SUCCESS = 'DOWNLOAD_EXCEL_TEMPLATE_SUCCESS';
export const DOWNLOAD_EXCEL_TEMPLATE_ERROR = 'DOWNLOAD_EXCEL_TEMPLATE_ERROR';