export const GET_INIT_STATE = "INIT_EMPSTATUSLIST_STATE";

export const GET_EMP_STATUS_LIST_LOADING = 'GET_EMP_STATUS_LIST_LOADING';
export const GET_EMP_STATUS_LIST_SUCCESS = 'GET_EMP_STATUS_LIST_SUCCESS';
export const GET_EMP_STATUS_LIST_ERROR = 'GET_EMP_STATUS_LIST_ERROR';

export const GET_EMP_STATUS_LIST_PAGE_COUNT_LOADING = 'GET_EMP_STATUS_LIST_PAGE_COUNT_LOADING';
export const GET_EMP_STATUS_LIST_PAGE_COUNT_SUCCESS = 'GET_EMP_STATUS_LIST_PAGE_COUNT_SUCCESS';
export const GET_EMP_STATUS_LIST_PAGE_COUNT_ERROR = 'GET_EMP_STATUS_LIST_PAGE_COUNT_ERROR';

export const GET_TAG_INFO_LOADING = 'GET_TAG_INFO_EMP_LOADING';
export const GET_TAG_INFO_SUCCESS = 'GET_TAG_INFO_EMP_SUCCESS';
export const GET_TAG_INFO_ERROR = 'GET_TAG_INFO_EMP_ERROR';