export const GET_INIT_STATE = 'GET_INIT_STATE';

export const GET_ORG_DATA = 'GET_ORG_DATA';

export const SHOW_MODAL_TYPE = 'SHOW_MODAL_TYPE';

export const CHECK_ORG_DATA_LOADING = 'CHECK_ORG_DATA_LOADING';
export const CHECK_ORG_DATA_SUCCESS = 'CHECK_ORG_DATA_SUCCESS';
export const CHECK_ORG_DATA_ERROR = 'CHECK_ORG_DATA_ERROR';

export const SEARCH_VENDOR_LOADING = 'SEARCH_VENDOR_LOADING';
export const SEARCH_VENDOR_SUCCESS = 'SEARCH_VENDOR_SUCCESS';
export const SEARCH_VENDOR_ERROR = 'SEARCH_VENDOR_ERROR';

export const ADD_ORG_DATA_LOADING = 'ADD_ORG_DATA_LOADING';
export const ADD_ORG_DATA_SUCCESS = 'ADD_ORG_DATA_SUCCESS';
// export const ADD_ORG_DATA_ERROR = 'ADD_ORG_DATA_ERROR';
