export const INIT_STATE = 'INIT_EMP_DETAILS_STATE';
export const RESET_ERROR = 'RESET_EMP_DETAILS_ERROR';

export const GET_DATA_LOADING = 'GET_EMP_DETAILS_LOADING';
export const GET_DATA_SUCCESS = 'GET_EMP_DETAILS_SUCCESS';
export const GET_DATA_ERROR = 'GET_EMP_DETAILS_ERROR';

export const GET_ORG_DATA_LOADING = 'GET_ORG_DETAILS_LOADING';
export const GET_ORG_DATA_SUCCESS = 'GET_ORG_DETAILS_SUCCESS';
export const GET_ORG_DATA_ERROR = 'GET_ORG_DETAILS_ERROR';

export const GET_REPORTS_TO_DATA_LOADING = 'GET_REPORTS_TO_DATA_LOADING';
export const GET_REPORTS_TO_DATA_SUCCESS = 'GET_REPORTS_TO_DATA_SUCCESS';
export const GET_REPORTS_TO_DATA_ERROR = 'GET_REPORTS_TO_DATA_ERROR';

export const GET_REPORTS_TO_TAG_INFO_LOADING = 'GET_REPORTS_TO_TAG_INFO_LOADING';
export const GET_REPORTS_TO_TAG_INFO_SUCCESS = 'GET_REPORTS_TO_TAG_INFO_SUCCESS';
export const GET_REPORTS_TO_TAG_INFO_ERROR = 'GET_REPORTS_TO_TAG_INFO_ERROR';

export const GET_SHARED_TAG_INFO_LOADING = 'GET_SHARED_TAG_INFO_LOADING';
export const GET_SHARED_TAG_INFO_SUCCESS = 'GET_SHARED_TAG_INFO_SUCCESS';
export const GET_SHARED_TAG_INFO_ERROR = 'GET_SHARED_TAG_INFO_ERROR';

export const PUT_DATA_LOADING = 'PUT_EMP_DETAILS_LOADING';
export const PUT_DATA_SUCCESS = 'PUT_EMP_DETAILS_SUCCESS';
export const PUT_DATA_ERROR = 'PUT_EMP_DETAILS_ERROR';

export const GET_ENTITY_TYPE = 'GET_ENTITY_TYPE';
export const SET_REPORTS_TO_DATA = 'SET_REPORTS_TO_DATA_SUCCESS';

export const GET_TAG_INFO_LOADING = 'GET_TAG_INFO_EMPDETAILS_LOADING';
export const GET_TAG_INFO_SUCCESS = 'GET_TAG_INFO_EMPDETAILS_SUCCESS';
export const GET_TAG_INFO_ERROR = 'GET_TAG_INFO_EMPDETAILS_ERROR';

export const GET_DEPLOYMENT_HISTORY_LOADING = 'GET_DEPLOYMENT_HISTORY_LOADING';
export const GET_DEPLOYMENT_HISTORY_SUCCESS = 'GET_DEPLOYMENT_HISTORY_SUCCESS';
export const GET_DEPLOYMENT_HISTORY_ERROR = 'GET_DEPLOYMENT_HISTORY_ERROR';

export const GET_CONTRACTOR_DETAILS_LOADING = 'GET_CONTRACTOR_DETAILS_LOADING';
export const GET_CONTRACTOR_DETAILS_SUCCESS = 'GET_CONTRACTOR_DETAILS_SUCCESS';
export const GET_CONTRACTOR_DETAILS_ERROR = 'GET_CONTRACTOR_DETAILS_ERROR';

export const PUT_CONTRACTOR_DETAILS_LOADING = 'PUT_CONTRACTOR_DETAILS_LOADING';
export const PUT_CONTRACTOR_DETAILS_SUCCESS = 'PUT_CONTRACTOR_DETAILS_SUCCESS';
export const PUT_CONTRACTOR_DETAILS_ERROR = 'PUT_CONTRACTOR_DETAILS_ERROR';

export const GET_ORG_LIST_INFO_LOADING = 'GET_ORG_LIST_INFO_LOADING';
export const GET_ORG_LIST_INFO_SUCCESS = 'GET_ORG_LIST_INFO_SUCCESS';
export const GET_ORG_LIST_INFO_ERROR = 'GET_ORG_LIST_INFO_ERROR';
