export const INIT_STATE = 'INIT_POSTAL_ADDRESS_VERIFICATION_STATE';

export const GET_AGENCY_LIST_LOADING = 'GET_AGENCY_LIST_LOADING';
export const GET_AGENCY_LIST_SUCCESS = 'GET_AGENCY_LIST_SUCCESS';
export const GET_AGENCY_LIST_ERROR = 'GET_AGENCY_LIST_ERROR';

// export const GET_INDIVIDUAL_TASK_LOADING = 'GET_INDIVIDUAL_TASK_LOADING';
// export const GET_INDIVIDUAL_TASK_SUCCESS = 'GET_INDIVIDUAL_TASK_SUCCESS';
// export const GET_INDIVIDUAL_TASK_ERROR = 'GET_INDIVIDUAL_TASK_ERROR';

export const GET_TAG_NAME_LOADING = 'GET_TAG_NAME_SPOC_LOADING';
export const GET_TAG_NAME_SUCCESS = 'GET_TAG_NAME_SPOC_SUCCESS';
export const GET_TAG_NAME_ERROR = 'GET_TAG_NAME_SPOC_ERROR';

// export const POST_INDIVIDUAL_TASK_LOADING = 'POST_INDIVIDUAL_TASK_LOADING';
// export const POST_INDIVIDUAL_TASK_SUCCESS = 'POST_INDIVIDUAL_TASK_SUCCESS';
// export const POST_INDIVIDUAL_TASK_ERROR = 'POST_INDIVIDUAL_TASK_ERROR';

export const GET_INDIVIDUAL_TASK_NOTIFICATION = 'GET_INDIVIDUAL_TASK_NOTIFICATION';

export const GET_POSTAL_TASK_DETAILS_LOADING = 'GET_POSTAL_TASK_DETAILS_SPOC_LOADING';
export const GET_POSTAL_TASK_DETAILS_SUCCESS = 'GET_POSTAL_TASK_DETAILS_SPOC_SUCCESS';
export const GET_POSTAL_TASK_DETAILS_ERROR = 'GET_POSTAL_TASK_DETAILS_SPOC_ERROR';

export const POST_POSTAL_TASK_DETAILS_LOADING = 'POST_POSTAL_TASK_DETAILS_SPOC_LOADING';
export const POST_POSTAL_TASK_DETAILS_SUCCESS = 'POST_POSTAL_TASK_DETAILS_SPOC_SUCCESS';
export const POST_POSTAL_TASK_DETAILS_ERROR = 'POST_POSTAL_TASK_DETAILS_SPOC_ERROR';