export const POST_TAT_DATA_LOADING = 'POST_TAT_DATA_LOADING';
export const POST_TAT_DATA_SUCCESS = 'POST_TAT_DATA_SUCCESS';
export const POST_TAT_DATA_ERROR = 'POST_TAT_DATA_ERROR';

export const GET_SERVICE_DATA_LOADING = 'GET_SERVICE_DATA_LOADING';
export const GET_SERVICE_DATA_SUCCESS = 'GET_SERVICE_DATA_SUCCESS';
export const GET_SERVICE_DATA_ERROR = 'GET_SERVICE_DATA_ERROR';

export const PUT_TAT_DATA_LOADING = 'PUT_TAT_DATA_LOADING';
export const PUT_TAT_DATA_SUCCESS = 'PUT_TAT_DATA_SUCCESS';
export const  PUT_TAT_DATA_ERROR = 'PUT_TAT_DATA_ERROR';

export const GET_INIT_STATE = 'GET_INIT_STATE';