export const INIT_STATE = 'INIT_EMP_ONBOARD_STATE';

export const GET_STATIC_DATA_LOADING = 'ONBOARD_GET_STATIC_DATA_LOADING';
export const GET_STATIC_DATA_SUCCESS = 'ONBOARD_GET_STATIC_DATA_SUCCESS';
export const GET_STATIC_DATA_ERROR = 'ONBOARD_GET_STATIC_DATA_ERROR';

export const GET_EMPLOYEE_DATA_LOADING = 'GET_EMPLOYEE_DATA_LOADING';
export const GET_EMPLOYEE_DATA_SUCCESS = 'GET_EMPLOYEE_DATA_SUCCESS';
export const GET_EMPLOYEE_DATA_ERROR = 'GET_EMPLOYEE_DATA_ERROR';

export const UPDATE_EMPLOYEE_DATA_LOADING = 'UPDATE_EMPLOYEE_DATA_LOADING';
export const UPDATE_EMPLOYEE_DATA_SUCCESS = 'UPDATE_EMPLOYEE_DATA_SUCCESS';
export const UPDATE_EMPLOYEE_DATA_ERROR = 'UPDATE_EMPLOYEE_DATA_ERROR';

export const GET_EMPLOYEE_PROFILE_PIC_LOADING = 'GET_EMPLOYEE_PROFILE_PIC_LOADING';
export const GET_EMPLOYEE_PROFILE_PIC_SUCCESS = 'GET_EMPLOYEE_PROFILE_PIC_SUCCESS';
export const GET_EMPLOYEE_PROFILE_PIC_ERROR = 'GET_EMPLOYEE_PROFILE_PIC_ERROR';

export const REMOVE_EMPLOYEE_PROFILE_PIC = 'REMOVE_EMPLOYEE_PROFILE_PIC';

export const GET_EMPLOYEE_DEFAULT_ROLE_LOADING = 'GET_EMPLOYEE_DEFAULT_ROLE_LOADING';
export const GET_EMPLOYEE_DEFAULT_ROLE_SUCCESS = 'GET_EMPLOYEE_DEFAULT_ROLE_SUCCESS';
export const GET_EMPLOYEE_DEFAULT_ROLE_ERROR = 'GET_EMPLOYEE_DEFAULT_ROLE_ERROR';

export const UPDATE_SECTION_STATUS = 'UPDATE_EMPLOYEE_SECTION_STATUS';

export const GET_EMPLOYEE_BGV_DATA_LOADING = 'EMP_ONBOARD_GET_EMPLOYEE_BGV_DATA_LOADING';
export const GET_EMPLOYEE_BGV_DATA_SUCCESS = 'EMP_ONBOARD_GET_EMPLOYEE_BGV_DATA_SUCCESS';
export const GET_EMPLOYEE_BGV_DATA_ERROR = 'EMP_ONBOARD_GET_EMPLOYEE_BGV_DATA_ERROR';

export const GET_EMP_MISSING_INFO_LOADING = 'EMP_ONBOARD_GET_EMP_MISSING_INFO_LOADING';
export const GET_EMP_MISSING_INFO_SUCCESS = 'EMP_ONBOARD_GET_EMP_MISSING_INFO_SUCCESS';
export const GET_EMP_MISSING_INFO_ERROR = 'EMP_ONBOARD_GET_EMP_MISSING_INFO_ERROR';

export const UPLOAD_DOCUMENT_LOADING = "UPLOAD_EMP_ONBOARD_DOCUMENT_LOADING";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_EMP_ONBOARD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_ERROR = "UPLOAD_EMP_ONBOARD_DOCUMENT_ERROR";

export const DOWNLOAD_DOCUMENT_LOADING = "DOWNLOAD_EMP_ONBOARD_DOCUMENT_LOADING";
export const DOWNLOAD_DOCUMENT_SUCCESS = "DOWNLOAD_EMP_ONBOARD_DOCUMENT_SUCCESS";
export const DOWNLOAD_DOCUMENT_ERROR = "DOWNLOAD_EMP_ONBOARD_DOCUMENT_ERROR";

export const GENERATE_DOCUMENT_LOADING = "EMP_ONBOARD_GENERATE_DOCUMENT_LOADING";
export const GENERATE_DOCUMENT_SUCCESS = "EMP_ONBOARD_GENERATE_DOCUMENT_SUCCESS";
export const GENERATE_DOCUMENT_ERROR = "EMP_ONBOARD_GENERATE_DOCUMENT_ERROR";

export const SAVE_DOCUMENT_LOADING = "EMP_ONBOARD_SAVE_DOCUMENT_LOADING";
export const SAVE_DOCUMENT_SUCCESS = "EMP_ONBOARD_SAVE_DOCUMENT_SUCCESS";
export const SAVE_DOCUMENT_ERROR = "EMP_ONBOARD_SAVE_DOCUMENT_ERROR";

export const GET_EMPLOYEE_REPORTING_MANAGER_LOADING = "EMP_ONBOARD_GET_EMPLOYEE_REPORTING_MANAGER_LOADING";
export const GET_EMPLOYEE_REPORTING_MANAGER_SUCCESS = "EMP_ONBOARD_GET_EMPLOYEE_REPORTING_MANAGER_SUCCESS";
export const GET_EMPLOYEE_REPORTING_MANAGER_ERROR = "EMP_ONBOARD_GET_EMPLOYEE_REPORTING_MANAGER_ERROR";