export const GET_VENDOR_TAGS_LOADING = "GET_VENDOR_TAGS_LOADING";
export const GET_VENDOR_TAGS_SUCCESS = "GET_VENDOR_TAGS_SUCCESS";
export const GET_VENDOR_TAGS_ERROR = "GET_VENDOR_TAGS_ERROR";

export const GET_ORG_NAME_LOADING = "GET_ORG_NAME_LOADING";
export const GET_ORG_NAME_SUCCESS = "GET_ORG_NAME_SUCCESS";
export const GET_ORG_NAME_ERROR = "GET_ORG_NAME_ERROR";

export const GET_VENDOR_DATA_LOADING = 'GET_VENDOR_DATA_LOADING';
export const GET_VENDOR_DATA_SUCCESS = 'GET_VENDOR_DATA_SUCCESS';
export const GET_VENDOR_DATA_ERROR = 'GET_VENDOR_DATA_ERROR';