export const INIT_VENDOR_FILTERS = 'INIT_VENDOR_FILTERS';

export const SEARCH_VENDOR_LIST_LOADING = 'SEARCH_VENDOR_LIST_LOADING';
export const SEARCH_VENDOR_LIST_SUCCESS = 'SEARCH_VENDOR_LIST_SUCCESS';
export const SEARCH_VENDOR_LIST_ERROR = 'SEARCH_VENDOR_LIST_SUCCESS';

export const SEARCH_CLIENT_LIST_LOADING = 'SEARCH_CLIENT_LIST_LOADING';
export const SEARCH_CLIENT_LIST_SUCCESS = 'SEARCH_CLIENT_LIST_SUCCESS';
export const SEARCH_CLIENT_LIST_ERROR = 'SEARCH_CLIENT_LIST_ERROR';

export const GET_SUBVENDOR_LIST_LOADING = 'GET_SUBVENDOR_LIST_LOADING';
export const GET_SUBVENDOR_LIST_SUCCESS = 'GET_SUBVENDOR_LIST_SUCCESS';
export const GET_SUBVENDOR_LIST_ERROR = 'GET_SUBVENDOR_LIST_ERROR';

export const GET_SUPERCLIENT_LIST_LOADING = 'GET_SUPERCLIENT_LIST_LOADING';
export const GET_SUPERCLIENT_LIST_SUCCESS = 'GET_SUPERCLIENT_LIST_SUCCESS';
export const GET_SUPERCLIENT_LIST_ERROR = 'GET_SUPERCLIENT_LIST_ERROR';
