export const INIT_STATE = 'INIT_ORG_DOCUMENT_STATE';
export const RESET_ERROR = 'RESET_ORG_DOCUMENT_ERROR';

export const RESET_DOWNLOAD_URL_LIST = 'RESET_DOWNLOAD_URL_LIST_ORG_DOCUMENT';
export const RESET_DELETE_URL = 'RESET_DELETE_URL_ORG_DOCUMENT';

export const GET_DATA_LIST_LOADING = 'GET_ORG_DOCUMENT_LIST_LOADING';
export const GET_DATA_LIST_SUCCESS = 'GET_ORG_DOCUMENT_LIST_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_ORG_DOCUMENT_LIST_ERROR';

export const POST_DATA_LOADING = 'POST_ORG_DOCUMENT_LOADING';
export const POST_DATA_SUCCESS = 'POST_ORG_DOCUMENT_SUCCESS';
export const POST_DATA_ERROR = 'POST_ORG_DOCUMENT_ERROR';

export const PUT_DATA_LOADING = 'PUT_ORG_DOCUMENT_LOADING';
export const PUT_DATA_SUCCESS = 'PUT_ORG_DOCUMENT_SUCCESS';
export const PUT_DATA_ERROR = 'PUT_ORG_DOCUMENT_ERROR';

export const DELETE_DATA_LOADING = 'DELETE_ORG_DOCUMENT_LOADING';
export const DELETE_DATA_SUCCESS = 'DELETE_ORG_DOCUMENT_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_ORG_DOCUMENT_ERROR';

export const UPLOAD_FILE_LOADING = 'UPLOAD_ORG_DOCUMENT_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_ORG_DOCUMENT_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_ORG_DOCUMENT_FILE_ERROR';

export const DELETE_FILE_LOADING = 'DELETE_ORG_DOCUMENT_FILE_LOADING';
export const DELETE_FILE_SUCCESS = 'DELETE_ORG_DOCUMENT_FILE_SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE_ORG_DOCUMENT_FILE_ERROR';

export const DOWNLOAD_FILE_LOADING = 'DOWNLOAD_DOCUMENT_FILE_LOADING';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_DOCUMENT_FILE_SUCCESS';
export const DOWNLOAD_FILE_ERROR = 'DOWNLOAD_DOCUMENT_FILE_ERROR';