export const INIT_STATE = 'DOWNLOAD_FILES_INIT_DATA_STATE'

export const DOWNLOAD_EMP_BGV_PDF_LOADING = 'DOWNLOAD_FILES_EMP_BGV_PDF_LOADING'
export const DOWNLOAD_EMP_BGV_PDF_SUCCESS = 'DOWNLOAD_FILES_EMP_BGV_PDF_SUCCESS'
export const DOWNLOAD_EMP_BGV_PDF_ERROR = 'DOWNLOAD_FILES_EMP_BGV_PDF_ERROR'