export const INIT_STATE = 'INIT_GET_IMAGES_STATE';

export const GET_PROFILE_PIC_LOADING = 'GET_PROFILE_PICTURES_LOADING';
export const GET_PROFILE_PIC_SUCCESS = 'GET_PROFILE_PICTURES_SUCCESS';
export const GET_PROFILE_PIC_ERROR = 'GET_PROFILE_PICTURES_ERROR';

export const GET_ADDRESS_PIC_LOADING = 'GET_ADDRESS_PIC_LOADING';
export const GET_ADDRESS_PIC_SUCCESS = 'GET_ADDRESS_PIC_SUCCESS';
export const GET_ADDRESS_PIC_ERROR = 'GET_ADDRESS_PIC_ERROR';

export const GET_ADDRESS_IMAGES_INTI_STATE = 'GET_ADDRESS_IMAGES_INTI_STATE';
