export const GET_INIT_STATE = 'GET_INIT_STATE';
export const RESET_ERROR = 'RESET_VENDOR_DETAILS_ERROR';

export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const POST_DATA_LOADING = 'POST_DATA_LOADING';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_ERROR = 'POST_DATA_ERROR';

export const GET_AGREEMENT_LOADING = 'GET_AGREEMENT_LOADING';
export const GET_AGREEMENT_SUCCESS = 'GET_AGREEMENT_SUCCESS';
export const GET_AGREEMENT_ERROR = 'GET_AGREEMENT_ERROR';

export const DELETE_AGREEMENT_LOADING = 'DELETE_AGREEMENT_LOADING';
export const DELETE_AGREEMENT_SUCCESS = 'DELETE_AGREEMENT_SUCCESS';
export const DELETE_AGREEMENT_ERROR = 'DELETE_AGREEMENT_ERROR';

export const GET_ORG_NAME_LOADING = 'GET_ORG_NAME_LOADING';
export const GET_ORG_NAME_SUCCESS = 'GET_ORG_NAME_SUCCESS';
export const GET_ORG_NAME_ERROR = 'GET_ORG_NAME_ERROR';

export const DOWNLOAD_FILE_LOADING = 'DOWNLOAD_DOCUMENT_FILE_LOADING';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_DOCUMENT_FILE_SUCCESS';
export const DOWNLOAD_FILE_ERROR = 'DOWNLOAD_DOCUMENT_FILE_ERROR';

export const PUT_VENDOR_DATA_LOADING = 'PUT_VENDOR_DATA_LOADING';
export const PUT_VENDOR_DATA_SUCCESS = 'PUT_VENDOR_DATA_SUCCESS';
export const PUT_VENDOR_DATA_ERROR = 'PUT_VENDOR_DATA_ERROR';

export const GET_VENDOR_CONTACTS_LOADING = 'GET_VENDOR_CONTACTS_LOADING';
export const GET_VENDOR_CONTACTS_SUCCESS = 'GET_VENDOR_CONTACTS_SUCCESS';
export const GET_VENDOR_CONTACTS_ERROR = 'GET_VENDOR_CONTACTS_ERROR';
