export const INIT_STATE = 'INIT_ADDNEW_STATE';

export const GET_PROFILEPIC_LOADING='GET_PROFILEPIC_LOADING';
export const GET_PROFILEPIC_SUCCESS='GET_PROFILEPIC_SUCCESS';
export const GET_PROFILEPIC_ERROR='GET_PROFILEPIC_ERROR';

export const DELETE_PROFILEPIC_LOADING='DELETE_PROFILEPIC_LOADING';
export const DELETE_PROFILEPIC_SUCCESS='DELETE_PROFILEPIC_SUCCESS';
export const DELETE_PROFILEPIC_ERROR='DELETE_PROFILEPIC_ERROR';

export const GET_CONSENT_LOADING='GET_CONSENT_LOADING';
export const GET_CONSENT_SUCCESS='GET_CONSENT_SUCCESS';
export const GET_CONSENT_ERROR='GET_CONSENT_ERROR';

export const DELETE_CONSENT_LOADING='DELETE_CONSENT_LOADING';
export const DELETE_CONSENT_SUCCESS='DELETE_CONSENT_SUCCESS';
export const DELETE_CONSENT_ERROR='DELETE_CONSENT_ERROR';

export const DOWNLOAD_CONSENT_POLICY_LOADING = 'DOWNLOAD_CONSENT_POLICY_LOADING';
export const DOWNLOAD_CONSENT_POLICY_SUCCESS = 'DOWNLOAD_CONSENT_POLICY_SUCCESS';
export const DOWNLOAD_CONSENT_POLICY_ERROR = 'DOWNLOAD_CONSENT_POLICY_ERROR';

export const DOWNLOAD_FILE_LOADING = 'DOWNLOAD_DOCUMENT_FILE_LOADING';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_DOCUMENT_FILE_SUCCESS';
export const DOWNLOAD_FILE_ERROR = 'DOWNLOAD_DOCUMENT_FILE_ERROR';

export const POST_DATA_LOADING = 'POST_ADD_NEW_EMP_LOADING';
export const POST_DATA_SUCCESS = 'POST_ADD_NEW_EMP_SUCCESS';
export const POST_DATA_ERROR = 'POST_ADD_NEW_EMP_ERROR';

export const GET_EMPLOYEE_PROFILE_PIC_LOADING = 'GET_EMPLOYEE_PROFILE_PIC_NEW_LOADING';
export const GET_EMPLOYEE_PROFILE_PIC_SUCCESS = 'GET_EMPLOYEE_PROFILE_PIC_NEW_SUCCESS';
export const GET_EMPLOYEE_PROFILE_PIC_ERROR = 'GET_EMPLOYEE_PROFILE_PIC_NEW_ERROR';