export const INIT_STATE = 'INIT_SERVICE_VERIFICATION_STATE';

export const GET_DOCUMENTS_TASKS_LOADING = 'GET_DOCUMENTS_TASKS_LOADING';
export const GET_DOCUMENTS_TASKS_ERROR = 'GET_DOCUMENTS_TASKS_ERROR';
export const GET_DOCUMENTS_TASKS_SUCCESS = 'GET_DOCUMENTS_TASKS_SUCCESS';

export const POST_DOCUMENTS_TASKS_LOADING = 'POST_DOCUMENTS_TASKS_LOADING';
export const POST_DOCUMENTS_TASKS_ERROR = 'POST_DOCUMENTS_TASKS_ERROR';
export const POST_DOCUMENTS_TASKS_SUCCESS = 'POST_DOCUMENTS_TASKS_SUCCESS';

export const POST_SMS_EMAIL_LOADING = 'POST_SMS_EMAIL_LOADING';
export const POST_SMS_EMAIL_ERROR = 'POST_SMS_EMAIL_ERROR';
export const POST_SMS_EMAIL_SUCCESS = 'POST_SMS_EMAIL_SUCCESS';

export const GET_IN_PROGRESS_TASKS_LOADING = 'GET_IN_PROGRESS_TASKS_LOADING';
export const GET_IN_PROGRESS_TASKS_SUCCESS = 'GET_IN_PROGRESS_TASKS_SUCCESS';
export const GET_IN_PROGRESS_TASKS_ERROR = 'GET_IN_PROGRESS_TASKS_ERROR';

export const GET_COMPLETED_TASKS_LOADING = 'GET_COMPLETED_TASKS_LOADING';
export const GET_COMPLETED_TASKS_SUCCESS = 'GET_COMPLETED_TASKS_SUCCESS';
export const GET_COMPLETED_TASKS_ERROR = 'GET_COMPLETED_TASKS_ERROR';

export const PUT_WORKLOAD_TRANSFERDATA_LOADING = 'PUT_WORKLOAD_TRANSFERDATA_LOADING';
export const PUT_WORKLOAD_TRANSFERDATA_SUCCESS = 'PUT_WORKLOAD_TRANSFERDATA_SUCCESS';
export const PUT_WORKLOAD_TRANSFERDATA_ERROR = 'PUT_WORKLOAD_TRANSFERDATA_ERROR';

export const GET_USER_NAME_LOADING = 'GET_USER_NAME_LOADING';
export const GET_USER_NAME_SUCCESS = 'GET_USER_NAME_SUCCESS';
export const GET_USER_NAME_ERROR = 'GET_USER_NAME_ERROR';

export const GET_COMMENTS_LOADING = 'GET_COMMENTS_LOADING';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const DOWNLOAD_TASK_POC_LOADING = 'DOWNLOAD_TASK_POC_LOADING';
export const DOWNLOAD_TASK_POC_SUCCESS = 'DOWNLOAD_TASK_POC_SUCCESS';
export const DOWNLOAD_TASK_POC_ERROR = 'DOWNLOAD_TASK_POC_ERROR';

export const GET_EXCEL_COUNT_LOADING = 'GET_EXCEL_COUNT_LOADING';
export const GET_EXCEL_COUNT_SUCCESS = 'GET_EXCEL_COUNT_SUCCESS';
export const GET_EXCEL_COUNT_ERROR = 'GET_EXCEL_COUNT_ERROR';

export const GET_TAG_INFO_LOADING = 'GET_TAG_INFO_WORKLOADMGMT_LOADING';
export const GET_TAG_INFO_SUCCESS = 'GET_TAG_INFO_WORKLOADMGMT_SUCCESS';
export const GET_TAG_INFO_ERROR = 'GET_TAG_INFO_WORKLOADMGMT_ERROR';

export const EXCEL_DOWNLOAD_TASKS_LOADING = 'EXCEL_DOWNLOAD_TASKS_LOADING';
export const EXCEL_DOWNLOAD_TASKS_SUCCESS = 'EXCEL_DOWNLOAD_TASKS_SUCCESS';
export const EXCEL_DOWNLOAD_TASKS_ERROR = 'EXCEL_DOWNLOAD_TASKS_ERROR';

export const EXCEL_TASKS_COUNT_LOADING = 'EXCEL_TASKS_COUNT_LOADING';
export const EXCEL_TASKS_COUNT_SUCCESS = 'EXCEL_TASKS_COUNT_SUCCESS';
export const EXCEL_TASKS_COUNT_ERROR = 'EXCEL_TASKS_COUNT_ERROR';

export const EXCEL_UPLOAD_TASKS_LOADING = 'EXCEL_UPLOAD_TASKS_LOADING';
export const EXCEL_UPLOAD_TASKS_SUCCESS = 'EXCEL_UPLOAD_TASKS_SUCCESS';
export const EXCEL_UPLOAD_TASKS_ERROR = 'EXCEL_UPLOAD_TASKS_ERROR';

export const PROCESS_UPLOADED_TASKS_LOADING = 'PROCESS_UPLOADED_TASKS_LOADING';
export const PROCESS_UPLOADED_TASKS_SUCCESS = 'PROCESS_UPLOADED_TASKS_SUCCESS';
export const PROCESS_UPLOADED_TASKS_ERROR = 'PROCESS_UPLOADED_TASKS_ERROR';

export const EXCEL_ERROR_DOWNLOAD_TASKS_LOADING = 'EXCEL_ERROR_DOWNLOAD_TASKS_LOADING';
export const EXCEL_ERROR_DOWNLOAD_TASKS_SUCCESS = 'EXCEL_ERROR_DOWNLOAD_TASKS_SUCCESS';
export const EXCEL_ERROR_DOWNLOAD_TASKS_ERROR = 'EXCEL_ERROR_DOWNLOAD_TASKS_ERROR';

export const ADDRESS_AGENCY_COUNT_LOADING = 'ADDRESS_AGENCY_COUNT_LOADING';
export const ADDRESS_AGENCY_COUNT_SUCCESS = 'ADDRESS_AGENCY_COUNT_SUCCESS';
export const ADDRESS_AGENCY_COUNT_ERROR = 'ADDRESS_AGENCY_COUNT_ERROR';