export const INIT_STATE = 'INIT_ASSOCIATED_ORG_SEARCH_STATE';

export const GET_ASSOCIATED_ORG_LIST_LOADING = 'GET_ASSOCIATED_ORG_LIST_LOADING';
export const GET_ASSOCIATED_ORG_LIST_SUCCESS = 'GET_ASSOCIATED_ORG_LIST_SUCCESS';
export const GET_ASSOCIATED_ORG_LIST_ERROR = 'GET_ASSOCIATED_ORG_LIST_ERROR';

export const GET_SUBVENDOR_LIST_LOADING = 'GET_SUBVENDOR_LIST_LOADING';
export const GET_SUBVENDOR_LIST_SUCCESS = 'GET_SUBVENDOR_LIST_SUCCESS';
export const GET_SUBVENDOR_LIST_ERROR = 'GET_SUBVENDOR_LIST_ERROR';

export const GET_SUPERCLIENT_LIST_LOADING = 'GET_SUPERCLIENT_LIST_LOADING';
export const GET_SUPERCLIENT_LIST_SUCCESS = 'GET_SUPERCLIENT_LIST_SUCCESS';
export const GET_SUPERCLIENT_LIST_ERROR = 'GET_SUPERCLIENT_LIST_ERROR';
