export const GET_INIT_STATE = 'GET_INIT_STATE';

export const POST_TAT_DATA_LOADING = 'POST_TAT_DATA_LOADING';
export const POST_TAT_DATA_SUCCESS = 'POST_TAT_DATA_SUCCESS';
export const POST_TAT_DATA_ERROR = 'POST_TAT_DATA_ERROR';

export const GET_SERVICE_DATA_LOADING = 'GET_SERVICE_DATA_LOADING';
export const GET_SERVICE_DATA_SUCCESS = 'GET_SERVICE_DATA_SUCCESS';
export const GET_SERVICE_DATA_ERROR = 'GET_SERVICE_DATA_ERROR';

export const PUT_TAT_DATA_LOADING = 'PUT_TAT_DATA_LOADING';
export const PUT_TAT_DATA_SUCCESS = 'PUT_TAT_DATA_SUCCESS';
export const  PUT_TAT_DATA_ERROR = 'PUT_TAT_DATA_ERROR';

export const GET_SELECTED_SERVICE_DATA_LOADING = 'GET_SELECTED_SERVICE_DATA_LOADING';
export const GET_SELECTED_SERVICE_DATA_SUCCESS = 'GET_SELECTED_SERVICE_DATA_SUCCESS';
export const GET_SELECTED_SERVICE_DATA_ERROR = 'GET_SELECTED_SERVICE_DATA_ERROR';

export const GET_ENABLED_PLATFORM_SERVICES_LOADING='GET_ENABLED_PLATFORM_SERVICES_LOADING';
export const GET_ENABLED_PLATFORM_SERVICES_SUCCESS='GET_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const GET_ENABLED_PLATFORM_SERVICES_ERROR='GET_ENABLED_PLATFORM_SERVICES_ERROR';

export const POST_ENABLED_PLATFORM_SERVICES_LOADING='POST_ENABLED_PLATFORM_SERVICES_LOADING';
export const POST_ENABLED_PLATFORM_SERVICES_SUCCESS='POST_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const POST_ENABLED_PLATFORM_SERVICES_ERROR='POST_ENABLED_PLATFORM_SERVICES_ERROR';

export const PUT_ENABLED_PLATFORM_SERVICES_LOADING='PUT_ENABLED_PLATFORM_SERVICES_LOADING';
export const PUT_ENABLED_PLATFORM_SERVICES_SUCCESS='PUT_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const PUT_ENABLED_PLATFORM_SERVICES_ERROR='PUT_ENABLED_PLATFORM_SERVICES_ERROR';
