export const ENTITY_TERMINATE_LOADING = 'ENTITY_TERMINATE_LOADING';
export const ENTITY_TERMINATE_SUCCESS = 'ENTITY_TERMINATE_SUCCESS';
export const ENTITY_TERMINATE_ERROR = 'ENTITY_TERMINATE_ERROR';

export const GET_TERMINATE_INIT_STATE = 'GET_TERMINATE_INIT_STATE';

export const SAVE_ENTITY_DATA = 'SAVE_ENTITY_DATA';

export const RESET_ERROR = 'RESET_EMP_DETAILS_ERROR';