export const GET_INIT_STATE = 'GET_INIT_STATE';
export const RESET_ERROR = 'RESET_BGV_CONFIG_ERROR';

export const GET_CONTACTS_LIST_LOADING = 'GET_CONTACTS_LIST_LOADING';
export const GET_CONTACTS_LIST_ERROR = 'GET_CONTACTS_LIST_ERROR';
export const GET_CONTACTS_LIST_SUCCESS = 'GET_CONTACTS_LIST_SUCCESS';

export const UPDATE_POSTED_SPOCS = 'UPDATE_POSTED_SPOCS';

export const POST_CLIENT_SPOCS_LOADING = 'POST_CLIENT_SPOCS_LOADING';
export const POST_CLIENT_SPOCS_ERROR = 'POST_CLIENT_SPOCS_ERROR';
export const POST_CLIENT_SPOCS_SUCCESS = 'POST_CLIENT_SPOCS_SUCCESS';

export const GET_CLIENT_SPOCS_LOADING = 'GET_CLIENT_SPOCS_LOADING';
export const GET_CLIENT_SPOCS_ERROR = 'GET_CLIENT_SPOCS_ERROR';
export const GET_CLIENT_SPOCS_SUCCESS = 'GET_CLIENT_SPOCS_SUCCESS';
