export const INIT_STATE = "ORG_ONBOARD_DOCUMENT_INIT_STATE"

export const DOCUMENT_PROCESS_LOADING = "ORG_ONBOARD_DOCUMENT_PROCESS_LOADING";
export const DOCUMENT_PROCESS_SUCCESS = "ORG_ONBOARD_DOCUMENT_PROCESS_SUCCESS";
export const DOCUMENT_PROCESS_ERROR = "ORG_ONBOARD_DOCUMENT_PROCESS_ERROR";
