export const INIT_STATE = 'INIT_STATE';

export const GET_CLIENT_DATA_LOADING = 'GET_CLIENT_DATA_LOADING';
export const GET_CLIENT_DATA_SUCCESS = 'GET_CLIENT_DATA_SUCCESS';
export const GET_CLIENT_DATA_ERROR = 'GET_CLIENT_DATA_ERROR';

export const GET_ORG_NAME_LOADING = "GET_ORG_NAME_LOADING";
export const GET_ORG_NAME_SUCCESS = "GET_ORG_NAME_SUCCESS";
export const GET_ORG_NAME_ERROR = "GET_ORG_NAME_ERROR";