export const GET_CARD_COMMENTS_LOADING="GET_CARD_COMMENTS_LOADING";
export const GET_CARD_COMMENTS_SUCCESS="GET_CARD_COMMENTS_SUCCESS";
export const GET_CARD_COMMENTS_ERROR="GET_CARD_COMMENTS_ERROR";

export const ADD_IMAGE_LOADING = 'ADD_DOCUMENT_LOADING';
export const ADD_IMAGE_SUCCESS = 'ADD_DOCUMENT_SUCCESS';
export const ADD_IMAGE_ERROR = 'ADD_DOCUMENT_ERROR';

export const DELETE_IMAGE_LOADING = 'DELETE_DOCUMENT_LOADING';
export const DELETE_IMAGE_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_IMAGE_ERROR = 'DELETE_DOCUMENT_ERROR';

export const UPLOAD_PHYSICAL_ADDRESS_LOADING = 'ADD_ADDRESS_URL_LOADING';
export const UPLOAD_PHYSICAL_ADDRESS_SUCCESS = 'ADD_ADDRESS_URL_SUCCESS';
export const UPLOAD_PHYSICAL_ADDRESS_ERROR = 'ADD_ADDRESS_URL_ERROR';

export const DELETE_PHYSICAL_ADDRESS_LOADING = 'DELETE_ADDRESS_URL_LOADING';
export const DELETE_PHYSICAL_ADDRESS_SUCCESS = 'DELETE_ADDRESS_URL_SUCCESS';
export const DELETE_PHYSICAL_ADDRESS_ERROR = 'DELETE_ADDRESS_URL_ERROR';

export const DOWNLOAD_ATTACHMENT_LOADING = 'DOWNLOAD_ATTACHMENT_LOADING';
export const DOWNLOAD_ATTACHMENT_SUCCESS = 'DOWNLOAD_ATTACHMENT_SUCCESS';
export const DOWNLOAD_ATTACHMENT_ERROR = 'DOWNLOAD_ATTACHMENT_ERROR';

export const INIT_STATE = 'INIT_WORKLOAD_MGMT_STATE';