export const errorMessages = {
    WORKLOAD_MGMT_AGENCY_CASE_DATE_RANGE: [],
    WORKLOAD_MGMT_AGENCY_CASE_STATUS: [],
    WORKLOAD_MGMT_AGENCY_STATE: [],
    WORKLOAD_MGMT_AGENCY_DISTRICT: [],
    WORKLOAD_MGMT_AGENCY_TALUK: [],
    WORKLOAD_MGMT_AGENCY_PINCODE: [],
    WORKLOAD_MGMT_AGENCY_TAT_LEFT: [],
}

export const data = [
    "WORKLOAD_MGMT_AGENCY_CASE_DATE_RANGE",
    // "WORKLOAD_MGMT_AGENCY_CASE_STATUS",
    "WORKLOAD_MGMT_AGENCY_TAT_LEFT",
    "WORKLOAD_MGMT_AGENCY_STATE",
]

export const locFilterData = {
    district: "WORKLOAD_MGMT_AGENCY_DISTRICT",
    city: "WORKLOAD_MGMT_AGENCY_TALUK",
    pincodes: "WORKLOAD_MGMT_AGENCY_PINCODE"
}

export const moreFilterData = [
    "WORKLOAD_MGMT_AGENCY_PINCODE"
]