export const INIT_STATE = 'INIT_ORG_LIST_STATE';

export const GET_DATA_LIST_SUCCESS = 'GET_ORG_LIST_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_ORG_LIST_ERROR';
export const GET_DATA_LIST_LOADING = 'GET_ORG_LIST_LOADING';

export const SET_PAGINATOR_COUNT = 'SET_PAGINATOR_COUNT';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const UPDATE_PAGINATOR = 'UPDATE_PAGINATOR';

export const GET_ORG_LIST_PAGINATION_DATA_LOADING = 'GET_ORG_LIST_PAGINATION_DATA_LOADING';
export const GET_ORG_LIST_PAGINATION_DATA_SUCCESS = 'GET_ORG_LIST_PAGINATION_DATA_SUCCESS';
export const GET_ORG_LIST_PAGINATION_DATA_ERROR = 'GET_ORG_LIST_PAGINATION_DATA_ERROR';

export const GET_ORG_LIST_PAGINATION_COUNT_LOADING = 'GET_ORG_LIST_PAGINATION_COUNT_LOADING';
export const GET_ORG_LIST_PAGINATION_COUNT_SUCCESS = 'GET_ORG_LIST_PAGINATION_COUNT_SUCCESS';
export const GET_ORG_LIST_PAGINATION_COUNT_ERROR = 'GET_ORG_LIST_PAGINATION_COUNT_ERROR';

export const GET_STARRED_ORG_LIST_LOADING = 'GET_STARRED_ORG_LIST_LOADING';
export const GET_STARRED_ORG_LIST_SUCCESS = 'GET_STARRED_ORG_LIST_SUCCESS';
export const GET_STARRED_ORG_LIST_ERROR = 'GET_STARRED_ORG_LIST_ERROR';

export const POST_STARRED_ORG_LOADING = 'POST_STARRED_ORG_LOADING';
export const POST_STARRED_ORG_SUCCESS = 'POST_STARRED_ORG_SUCCESS';
export const POST_STARRED_ORG_ERROR = 'POST_STARRED_ORG_ERROR';

export const DELETE_STARRED_ORG_LOADING = 'DELETE_STARRED_ORG_LOADING';
export const DELETE_STARRED_ORG_SUCCESS = 'DELETE_STARRED_ORG_SUCCESS';
export const DELETE_STARRED_ORG_ERROR = 'DELETE_STARRED_ORG_ERROR';



