export const INIT_STATE = 'INIT_TASK_LIST_STATE';

export const RESET_ERROR = 'RESET_TASK_LIST_ERROR';

export const SEARCH_AGENCY_EXECUTIVE_LOADING = 'SEARCH_AGENCY_EXECUTIVE_LOADING';
export const SEARCH_AGENCY_EXECUTIVE_SUCCESS = 'SEARCH_AGENCY_EXECUTIVE_SUCCESS';
export const SEARCH_AGENCY_EXECUTIVE_ERROR = 'SEARCH_AGENCY_EXECUTIVE_ERROR';

export const POST_ASSIGNMENT_LOADING = 'POST_ASSIGNMENT_LOADING';
export const POST_ASSIGNMENT_SUCCESS = 'POST_ASSIGNMENT_SUCCESS';
export const POST_ASSIGNMENT_ERROR = 'POST_ASSIGNMENT_ERROR';

export const DOWNLOAD_AGENCY_TASKS_LOADING = 'DOWNLOAD_AGENCY_TASKS_LOADING';
export const DOWNLOAD_AGENCY_TASKS_SUCCESS = 'DOWNLOAD_AGENCY_TASKS_SUCCESS';
export const DOWNLOAD_AGENCY_TASKS_ERROR = 'DOWNLOAD_AGENCY_TASKS_ERROR';

export const DOWNLOAD_POSTAL_TASKS_LOADING = 'DOWNLOAD_POSTAL_TASKS_LOADING';
export const DOWNLOAD_POSTAL_TASKS_SUCCESS = 'DOWNLOAD_POSTAL_TASKS_SUCCESS';
export const DOWNLOAD_POSTAL_TASKS_ERROR = 'DOWNLOAD_POSTAL_TASKS_ERROR';

export const EXCEL_UPLOAD_TASKS_LOADING = 'EXCEL_UPLOAD_TASKS_LOADING';
export const EXCEL_UPLOAD_TASKS_SUCCESS = 'EXCEL_UPLOAD_TASKS_SUCCESS';
export const EXCEL_UPLOAD_TASKS_ERROR = 'EXCEL_UPLOAD_TASKS_ERROR';

export const PROCESS_UPLOADED_TASKS_LOADING = 'PROCESS_UPLOADED_TASKS_LOADING';
export const PROCESS_UPLOADED_TASKS_SUCCESS = 'PROCESS_UPLOADED_TASKS_SUCCESS';
export const PROCESS_UPLOADED_TASKS_ERROR = 'PROCESS_UPLOADED_TASKS_ERROR';

export const EXCEL_ERROR_DOWNLOAD_TASKS_LOADING = 'EXCEL_ERROR_DOWNLOAD_TASKS_LOADING';
export const EXCEL_ERROR_DOWNLOAD_TASKS_SUCCESS = 'EXCEL_ERROR_DOWNLOAD_TASKS_SUCCESS';
export const EXCEL_ERROR_DOWNLOAD_TASKS_ERROR = 'EXCEL_ERROR_DOWNLOAD_TASKS_ERROR';

export const GET_POSTAL_UPLOAD_INIT_DATA = 'GET_POSTAL_UPLOAD_INIT_DATA';

export const GET_AGENCY_TASK_LIST_LOADING = 'GET_AGENCY_TASK_LIST_LOADING';
export const GET_AGENCY_TASK_LIST_SUCCESS = 'GET_AGENCY_TASK_LIST_SUCCESS';
export const GET_AGENCY_TASK_LIST_ERROR = 'GET_AGENCY_TASK_LIST_ERROR';