export const INIT_STATE = 'INIT_ADDRESS_STATE';
export const RESET_ERROR = 'RESET_ORG_ADDRESS_ERROR';

export const GET_DATA_LIST_LOADING = 'GET_ADDRESS_LIST_LOADING';
export const GET_DATA_LIST_SUCCESS = 'GET_ADDRESS_LIST_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_ADDRESS_LIST_ERROR';

export const POST_DATA_LOADING = 'POST_ADDRESS_LOADING';
export const POST_DATA_SUCCESS = 'POST_ADDRESS_SUCCESS';
export const POST_DATA_ERROR = 'POST_ADDRESS_ERROR';

export const PUT_DATA_LOADING = 'PUT_ADDRESS_LOADING';
export const PUT_DATA_SUCCESS = 'PUT_ADDRESS_SUCCESS';
export const PUT_DATA_ERROR = 'PUT_ADDRESS_ERROR';

export const DELETE_DATA_LOADING = 'DELETE_ADDRESS_LOADING';
export const DELETE_DATA_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_ADDRESS_ERROR';
