export const GET_INIT_STATE = "INIT_ONBAORD_DASHBOARD_STATE"

export const GET_ORG_DATA_LOADING = 'ONBOARD_DASHBOARD_GET_ORG_DATA_LOADING';
export const GET_ORG_DATA_SUCCESS = 'ONBOARD_DASHBOARD_GET_ORG_DATA_SUCCESS';
export const GET_ORG_DATA_ERROR = 'ONBOARD_DASHBOARD_GET_ORG_DATA_ERROR';

export const GET_ORG_CONFIG_LOADING = 'ONBOARD_DASHBOARD_GET_ORG_CONFIG_LOADING';
export const GET_ORG_CONFIG_SUCCESS = 'ONBOARD_DASHBOARD_GET_ORG_CONFIG_SUCCESS';
export const GET_ORG_CONFIG_ERROR = 'ONBOARD_DASHBOARD_GET_ORG_CONFIG_ERROR';

export const GET_ORG_BGV_CONFIG_LOADING = 'ONBOARD_DASHBOARD_GET_ORG_BGV_CONFIG_LOADING';
export const GET_ORG_BGV_CONFIG_SUCCESS = 'ONBOARD_DASHBOARD_GET_ORG_BGV_CONFIG_SUCCESS';
export const GET_ORG_BGV_CONFIG_ERROR = 'ONBOARD_DASHBOARD_GET_ORG_BGV_CONFIG_ERROR';

export const POST_ORG_BGV_DATA_LOADING = 'ONBOARD_DASHBOARD_POST_ORG_BGV_DATA_LOADING';
export const POST_ORG_BGV_DATA_SUCCESS = 'ONBOARD_DASHBOARD_POST_ORG_BGV_DATA_SUCCESS';
export const POST_ORG_BGV_DATA_ERROR = 'ONBOARD_DASHBOARD_POST_ORG_BGV_DATA_ERROR';

export const GET_ORG_ONBOARD_STATS_LOADING = 'ONBOARD_DASHBOARD_GET_ORG_ONBOARD_STATS_LOADING';
export const GET_ORG_ONBOARD_STATS_SUCCESS = 'ONBOARD_DASHBOARD_GET_ORG_ONBOARD_STATS_SUCCESS';
export const GET_ORG_ONBOARD_STATS_ERROR = 'ONBOARD_DASHBOARD_GET_ORG_ONBOARD_STATS_ERROR';

export const GET_ORG_ONBOARD_INSIGHTS_LOADING = 'ONBOARD_DASHBOARD_GET_ORG_ONBOARD_INSIGHTS_LOADING';
export const GET_ORG_ONBOARD_INSIGHTS_SUCCESS = 'ONBOARD_DASHBOARD_GET_ORG_ONBOARD_INSIGHTS_SUCCESS';
export const GET_ORG_ONBOARD_INSIGHTS_ERROR = 'ONBOARD_DASHBOARD_GET_ORG_ONBOARD_INSIGHTS_ERROR';