export const INIT_STATE = 'INIT_EMPLOYEE_LIST_STATE';

export const GET_FILTER_PAYLOAD_STATE = 'GET_FILTER_PAYLOAD_STATE';

export const GET_LIST_COUNT_LOADING = 'GET_LIST_COUNT_LOADING';
export const GET_LIST_COUNT_SUCCESS = 'GET_LIST_COUNT_SUCCESS';
export const GET_LIST_COUNT_ERROR = 'GET_LIST_COUNT_ERROR';

export const GET_EMPLOYEE_LIST_LOADING = 'GET_EMPLOYEE_LIST_LOADING';
export const GET_EMPLOYEE_LIST_SUCCESS = 'GET_EMPLOYEE_LIST_SUCCESS';
export const GET_EMPLOYEE_LIST_ERROR = 'GET_EMPLOYEE_LIST_ERROR';

export const SEARCH_EMP_COUNT_LOADING = 'SEARCH_EMP_COUNT_LOADING';
export const SEARCH_EMP_COUNT_SUCCESS = 'SEARCH_EMP_COUNT_SUCCESS';
export const SEARCH_EMP_COUNT_ERROR = 'SEARCH_EMP_COUNT_ERROR';

export const SEARCH_EMPLOYEE_LOADING = 'SEARCH_EMPLOYEE_LOADING';
export const SEARCH_EMPLOYEE_SUCCESS = 'SEARCH_EMPLOYEE_SUCCESS';
export const SEARCH_EMPLOYEE_ERROR = 'SEARCH_EMPLOYEE_ERROR';

export const POST_BULK_ACTION_EMPLOYEES_LOADING = 'POST_BULK_ACTION_EMPLOYEES_LOADING';
export const POST_BULK_ACTION_EMPLOYEES_SUCCESS = 'POST_BULK_ACTION_EMPLOYEES_SUCCESS';
export const POST_BULK_ACTION_EMPLOYEES_ERROR = 'POST_BULK_ACTION_EMPLOYEES_ERROR';

export const GET_TAG_INFO_LOADING = 'GET_TAG_INFO_EMP_LOADING';
export const GET_TAG_INFO_SUCCESS = 'GET_TAG_INFO_EMP_SUCCESS';
export const GET_TAG_INFO_ERROR = 'GET_TAG_INFO_EMP_ERROR';

export const GET_FILTER_TAG_MAP_LIST_LOADING = 'GET_FILTER_TAG_MAP_LIST_LOADING';
export const GET_FILTER_TAG_MAP_LIST_SUCCESS = 'GET_FILTER_TAG_MAP_LIST_SUCCESS';
export const GET_FILTER_TAG_MAP_LIST_ERROR = 'GET_FILTER_TAG_MAP_LIST_ERROR';

export const GET_CLIENT_SEARCH_LOADING = 'GET_CLIENT_SEARCH_LOADING';
export const GET_CLIENT_SEARCH_SUCCESS = 'GET_CLIENT_SEARCH_SUCCESS';
export const GET_CLIENT_SEARCH_ERROR = 'GET_CLIENT_SEARCH_ERROR';

export const GET_INITIATE_DATA_LOADING = 'GET_INITIATE_DATA_LOADING';
export const GET_INITIATE_DATA_SUCCESS = 'GET_INITIATE_DATA_SUCCESS';
export const GET_INITIATE_DATA_ERROR = 'GET_INITIATE_DATA_ERROR';

export const GET_DEPLOYED_EMPCOUNT_LOADING = 'GET_DEPLOYED_EMPCOUNT_LOADING';
export const GET_DEPLOYED_EMPCOUNT_SUCCESS = 'GET_DEPLOYED_EMPCOUNT_SUCCESS';
export const GET_DEPLOYED_EMPCOUNT_ERROR = 'GET_DEPLOYED_EMPCOUNT_ERROR';
