export const REFID_VALIDATE_LOADING = 'REFID_VALIDATE_LOADING';
export const REFID_VALIDATE_SUCCESS = 'REFID_VALIDATE_SUCCESS';
export const REFID_VALIDATE_ERROR = 'REFID_VALIDATE_ERROR';

export const GET_REFID_DETAILS_LOADING = 'GET_REFID_DETAILS_LOADING';
export const GET_REFID_DETAILS_SUCCESS = 'GET_REFID_DETAILS_SUCCESS';
export const GET_REFID_DETAILS_ERROR = 'GET_REFID_DETAILS_ERROR';

export const PUT_REFID_DETAILS_LOADING = 'PUT_REFID_DETAILS_LOADING';
export const PUT_REFID_DETAILS_SUCCESS = 'PUT_REFID_DETAILS_SUCCESS';
export const PUT_REFID_DETAILS_ERROR = 'PUT_REFID_DETAILS_ERROR';

// export const GET_TAG_NAME_LOADING = "GET_TAG_NAME_REF_LOADING";
// export const GET_TAG_NAME_SUCCESS = "GET_TAG_NAME_REF_SUCCESS";
// export const GET_TAG_NAME_ERROR = "GET_TAG_NAME_REF_ERROR";