export const INIT_STATE = "INIT_ACCESS_MGMT_STATE"
export const RESET_ERROR = "RESET_ACCESS_ERROR"

export const GET_LIST_OF_ORGS_LOADING = "GET_LIST_OF_ORGS_LOADING"
export const GET_LIST_OF_ORGS_SUCCESS = "GET_LIST_OF_ORGS_SUCCESS"
export const GET_LIST_OF_ORGS_ERROR = "GET_LIST_OF_ORGS_ERROR"

export const GET_ORG_DETAILS_LOADING = "GET_ORG_DETAILS_LOADING"
export const GET_ORG_DETAILS_SUCCESS = "GET_ORG_DETAILS_SUCCESS"
export const GET_ORG_DETAILS_ERROR = "GET_ORG_DETAILS_ERROR"

export const GET_PERMISSION_LIST_LOADING = "GET_PERMISSION_LIST_LOADING"
export const GET_PERMISSION_LIST_SUCCESS = "GET_PERMISSION_LIST_SUCCESS"
export const GET_PERMISSION_LIST_ERROR = "GET_PERMISSION_LIST_ERROR"

export const GET_POLICY_LOADING = "GET_POLICY_LOADING"
export const GET_POLICY_SUCCESS = "GET_POLICY_SUCCESS"
export const GET_POLICY_ERROR = "GET_POLICY_ERROR"

export const POST_POLICY_LOADING = "POST_POLICY_LOADING"
export const POST_POLICY_SUCCESS = "POST_POLICY_SUCCESS"
export const POST_POLICY_ERROR = "POST_POLICY_ERROR"

export const GET_ENABLED_PLATFORM_SERVICES_LOADING = 'GET_ENABLED_PLATFORM_SERVICES_LOADING'
export const GET_ENABLED_PLATFORM_SERVICES_SUCCESS = 'GET_ENABLED_PLATFORM_SERVICES_SUCCESS'
export const GET_ENABLED_PLATFORM_SERVICES_ERROR = 'GET_ENABLED_PLATFORM_SERVICES_ERROR'

export const POST_TAG_INFO_W_POLICY_LOADING = "POST_TAG_INFO_W_POLICY_LOADING"
export const POST_TAG_INFO_W_POLICY_SUCCESS = "POST_TAG_INFO_W_POLICY_SUCCESS"
export const POST_TAG_INFO_W_POLICY_ERROR = "POST_TAG_INFO_W_POLICY_ERROR"

export const POST_TAG_W_POLICY_LOADING = "POST_TAG_W_POLICY_LOADING"
export const POST_TAG_W_POLICY_SUCCESS = "POST_TAG_W_POLICY_SUCCESS"
export const POST_TAG_W_POLICY_ERROR = "POST_TAG_W_POLICY_ERROR"

export const GET_ORG_LIST_LOADING = "GET_ORG_LIST_LOADING"
export const GET_ORG_LIST_SUCCESS = "GET_ORG_LIST_SUCCESS"
export const GET_ORG_LIST_ERROR = "GET_ORG_LIST_ERROR"
export const CLEAR_SEARCH_LIST = "CLEAR_SEARCH_LIST"

export const DELETE_ORG_POLICY_LOADING = "DELETE_ORG_POLICY_LOADING"
export const DELETE_ORG_POLICY_SUCCESS = "DELETE_ORG_POLICY_SUCCESS"
export const DELETE_ORG_POLICY_ERROR = "DELETE_ORG_POLICY_ERROR"

export const UPDATE_TAG_ACCESS_LOADING = "UPDATE_TAG_ACCESS_LOADING"
export const UPDATE_TAG_ACCESS_SUCCESS = "UPDATE_TAG_ACCESS_SUCCESS"
export const UPDATE_TAG_ACCESS_ERROR = "UPDATE_TAG_ACCESS_ERROR"

export const UPDATE_POLICY_BY_TAGID_LOADING = "UPDATE_POLICY_BY_TAGID_LOADING"
export const UPDATE_POLICY_BY_TAGID_SUCCESS = "UPDATE_POLICY_BY_TAGID_SUCCESS"
export const UPDATE_POLICY_BY_TAGID_ERROR = "UPDATE_POLICY_BY_TAGID_ERROR"

export const DELETE_POLICY_LOADING = "DELETE_POLICY_LOADING"
export const DELETE_POLICY_SUCCESS = "DELETE_POLICY_SUCCESS"
export const DELETE_POLICY_ERROR = "DELETE_POLICY_ERROR"
