export const GET_DATA_LOADING = 'GET_PROFILE_LOADING';
export const GET_DATA_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_DATA_ERROR = 'GET_PROFILE_ERROR';

export const GET_ALL_EMP_LIST_LOADING = 'GET_ALL_EMP_LIST_LOADING';
export const GET_ALL_EMP_LIST_SUCCESS = 'GET_ALL_EMP_LIST_SUCCESS';
export const GET_ALL_EMP_LIST_ERROR = 'GET_ALL_EMP_LIST_ERROR';

export const GET_TAG_ID_INFO_LOADING = 'GET_TAG_ID_INFO_LOADING';
export const GET_TAG_ID_INFO_SUCCESS = 'GET_TAG_ID_INFO_SUCCESS';
export const GET_TAG_ID_INFO_ERROR = 'GET_TAG_ID_INFO_ERROR';

export const DOWNLOAD_CUSTOM_PDF_REPORT_LOADING = 'DOWNLOAD_CUSTOM_PDF_REPORT_LOADING';
export const DOWNLOAD_CUSTOM_PDF_REPORT_SUCCESS = 'DOWNLOAD_CUSTOM_PDF_REPORT_SUCCESS';
export const DOWNLOAD_CUSTOM_PDF_REPORT_ERROR = 'DOWNLOAD_CUSTOM_PDF_REPORT_ERROR';

export const GET_INIT_STATE = "INIT_BGVSTATUS_STATE"