//INIT STATE
export const INIT_TAGMGMT_STATE = 'INIT_TAGMGMT_STATE';

//SET ORG AND CATEGORY
export const SET_ORG_AND_CATEGORY = 'SET_ORG_AND_CATEGORY';

//NEW TAG TYPE
export const NEW_TAG_TYPE = 'NEW_TAG_TYPE';

//GET INIT STATE
export const GET_INIT_STATE = 'GET_INIT_STATE';

//TAGS LIST ACTIONS
export const GET_TAGS_LIST_LOADING = 'GET_TAGS_LIST_LOADING';
export const GET_TAGS_LIST_SUCCESS = 'GET_TAGS_LIST_SUCCESS';
export const GET_TAGS_LIST_ERROR = 'GET_TAGS_LIST_ERROR';

//TAG CRUD ACTIONS
export const GET_TAG_LOADING = 'GET_TAG_LOADING';
export const GET_TAG_SUCCESS = 'GET_TAG_SUCCESS';
export const GET_TAG_ERROR = 'GET_TAG_ERROR';

export const POST_TAG_LOADING = 'POST_TAG_LOADING';
export const POST_TAG_SUCCESS = 'POST_TAG_SUCCESS';
export const POST_TAG_ERROR = 'POST_TAG_ERROR';

export const PUT_TAG_LOADING = 'PUT_TAG_LOADING';
export const PUT_TAG_SUCCESS = 'PUT_TAG_SUCCESS';
export const PUT_TAG_ERROR = 'PUT_TAG_ERROR';

export const DELETE_TAG_LOADING = 'DELETE_TAG_LOADING';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_ERROR = 'DELETE_TAG_ERROR';

//SUBTAGS LIST ACTIONS
export const GET_SUBTAGS_LIST_LOADING = 'GET_SUBTAGS_LIST_LOADING';
export const GET_SUBTAGS_LIST_SUCCESS = 'GET_SUBTAGS_LIST_SUCCESS';
export const GET_SUBTAGS_LIST_ERROR = 'GET_SUBTAGS_LIST_ERROR';

//SUBTAG POST ACTIONS
export const POST_SUBTAG_LOADING = 'POST_SUBTAG_LOADING';
export const POST_SUBTAG_SUCCESS = 'POST_SUBTAG_SUCCESS';
export const POST_SUBTAG_ERROR = 'POST_SUBTAG_ERROR';

//COUNTRIES STATIC DATA
export const GET_STATIC_LIST_LOADING = 'GET_STATIC_LIST_LOADING';
export const GET_STATIC_LIST_SUCCESS = 'GET_STATIC_LIST_SUCCESS';
export const GET_STATIC_LIST_ERROR = 'GET_STATIC_LIST_ERROR';

//SEARCH STATIC TAGS ACTION

export const GET_SEARCH_TAG_LOADING = 'GET_SEARCH_TAG_LOADING';
export const GET_SEARCH_TAG_SUCCESS = 'GET_SEARCH_TAG_SUCCESS';
export const GET_SEARCH_TAG_ERROR = 'GET_SEARCH_TAG_ERROR';