export const INIT_STATE = 'INIT_EMP_MGMT_STATE';

export const GET_DATA_LIST_LOADING = 'GET_EMP_STATIC_DATA_LOADING';
export const GET_DATA_LIST_SUCCESS = 'GET_EMP_STATIC_DATA_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_EMP_STATIC_DATA_ERROR';

export const GET_ORG_DATA_LOADING = 'EMP_MGMT_GET_ORG_DETAILS_LOADING';
export const GET_ORG_DATA_SUCCESS = 'EMP_MGMT_GET_ORG_DETAILS_SUCCESS';
export const GET_ORG_DATA_ERROR = 'EMP_MGMT_GET_ORG_DETAILS_ERROR';

export const GET_SERVICES_ENABLED_LOADING = 'GET_SERVICES_ENABLED_LOADING';
export const GET_SERVICES_ENABLED_SUCCESS = 'GET_SERVICES_ENABLED_SUCCESS';
export const GET_SERVICES_ENABLED_ERROR = 'GET_SERVICES_ENABLED_ERROR';

export const GET_ORG_ONBOARD_CONFIG_LOADING = 'EMP_MGMT_GET_ORG_ONBOARD_CONFIG_LOADING';
export const GET_ORG_ONBOARD_CONFIG_SUCCESS = 'EMP_MGMT_GET_ORG_ONBOARD_CONFIG_SUCCESS';
export const GET_ORG_ONBOARD_CONFIG_ERROR = 'EMP_MGMT_GET_ORG_ONBOARD_CONFIG_ERROR';

export const GET_ORG_BGV_CONFIG_LOADING = 'EMP_MGMT_GET_ORG_BGV_CONFIG_LOADING';
export const GET_ORG_BGV_CONFIG_SUCCESS = 'EMP_MGMT_GET_ORG_BGV_CONFIG_SUCCESS';
export const GET_ORG_BGV_CONFIG_ERROR = 'GET_ORG_BGV_CONFIG_ERROR';