export const INIT_STATE = 'ATTEND_DASHBOARD_INIT';

export const GET_ATTEND_SITE_LIST_LOADING = 'SITE_SHIFT_MGMT_GET_SITES_LOADING';
export const GET_ATTEND_SITE_LIST_SUCCESS = 'SITE_SHIFT_MGMT_GET_SITES_SUCCESS';
export const GET_ATTEND_SITE_LIST_ERROR = 'SITE_SHIFT_MGMT_GET_SITES_ERROR';

export const GET_ATTEND_SITE_COUNT_LOADING = 'SITE_SHIFT_MGMT_GET_SITES_COUNT_LOADING';
export const GET_ATTEND_SITE_COUNT_SUCCESS = 'SITE_SHIFT_MGMT_GET_SITES_COUNT_SUCCESS';
export const GET_ATTEND_SITE_COUNT_ERROR = 'SITE_SHIFT_MGMT_GET_SITES_COUNT_ERROR';

export const POST_TAG_INFO_DATA_LOADING = 'SITE_SHIFT_MGMT_TAG_INFO_LOADING';
export const POST_TAG_INFO_DATA_SUCCESS = 'SITE_SHIFT_MGMT_TAG_INFO_SUCCESS';
export const POST_TAG_INFO_DATA_ERROR = 'SITE_SHIFT_MGMT_TAG_INFO_ERROR';
