export const INIT_VENDOR_TAGS_STATE = 'INIT_VENDOR_TAGS_STATE';

export const GET_VENDOR_TAGS_COUNT_LOADING = 'GET_VENDOR_TAGS_COUNT_LOADING';
export const GET_VENDOR_TAGS_COUNT_SUCCESS = 'GET_VENDOR_TAGS_COUNT_SUCCESS';
export const GET_VENDOR_TAGS_COUNT_ERROR = 'GET_VENDOR_TAGS_COUNT_ERROR';

export const GET_VENDOR_TAGS_LOADING = 'GET_VENDOR_TAGS_LOADING';
export const GET_VENDOR_TAGS_SUCCESS = 'GET_VENDOR_TAGS_SUCCESS';
export const GET_VENDOR_TAGS_ERROR = 'GET_VENDOR_TAGS_ERROR';

export const GET_ORG_NAME_LOADING = 'GET_ORG_NAME_LOADING';
export const GET_ORG_NAME_SUCCESS = 'GET_ORG_NAME_SUCCESS';
export const GET_ORG_NAME_ERROR = 'GET_ORG_NAME_ERROR';

export const GET_SELECTED_CLIENT_LOADING = 'GET_SELECTED_CLIENT_LOADING';
export const GET_SELECTED_CLIENT_SUCCESS = 'GET_SELECTED_CLIENT_SUCCESS';
export const GET_SELECTED_CLIENT_ERROR = 'GET_SELECTED_CLIENT_ERROR';

export const GET_VENDOR_DATA_LOADING = 'GET_VENDOR_DATA_LOADING';
export const GET_VENDOR_DATA_SUCCESS = 'GET_VENDOR_DATA_SUCCESS';
export const GET_VENDOR_DATA_ERROR = 'GET_VENDOR_DATA_ERROR';

export const GET_CLIENT_LIST_LOADING = 'GET_CLIENT_LIST_LOADING';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_ERROR = 'GET_CLIENT_LIST_ERROR';

export const POST_UNASSIGN_VENDOR_TAGS_LOADING = 'POST_UNASSIGN_VENDOR_TAGS_LOADING';
export const POST_UNASSIGN_VENDOR_TAGS_SUCCESS = 'POST_UNASSIGN_VENDOR_TAGS_SUCCESS';
export const POST_UNASSIGN_VENDOR_TAGS_ERROR = 'POST_UNASSIGN_VENDOR_TAGS_ERROR';

export const POST_SELECTED_FILTERS_TAG_DETAILS_LOADING = 'POST_SELECTED_FILTERS_TAG_DETAILS_LOADING';
export const POST_SELECTED_FILTERS_TAG_DETAILS_SUCCESS = 'POST_SELECTED_FILTERS_TAG_DETAILS_SUCCESS';
export const POST_SELECTED_FILTERS_TAG_DETAILS_ERROR = 'POST_SELECTED_FILTERS_TAG_DETAILS_ERROR';

export const POST_SELECTED_FILTERS_TAG_COUNT_LOADING = 'POST_SELECTED_FILTERS_TAG_COUNT_LOADING';
export const POST_SELECTED_FILTERS_TAG_COUNT_SUCCESS = 'POST_SELECTED_FILTERS_TAG_COUNT_SUCCESS';
export const POST_SELECTED_FILTERS_TAG_COUNT_ERROR = 'POST_SELECTED_FILTERS_TAG_COUNT_ERROR';
