export const INIT_STATE = 'INIT_STATE';

export const GET_DATA_LIST_LOADING = 'GET_ORG_LIST_LOADING';
export const GET_DATA_LIST_SUCCESS = 'GET_ORG_LIST_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_ORG_LIST_ERROR';

export const GET_CLIENT_NOTIFICATION_LOADING = 'GET_CLIENT_NOTIFICATION_LOADING';
export const GET_CLIENT_NOTIFICATION_SUCCESS = 'GET_CLIENT_NOTIFICATION_SUCCESS';
export const GET_CLIENT_NOTIFICATION_ERROR = 'GET_CLIENT_NOTIFICATION_ERROR';

export const PUT_CLIENT_NOTIFICATION_LOADING = 'PUT_CLIENT_NOTIFICATION_LOADING';
export const PUT_CLIENT_NOTIFICATION_SUCCESS = 'PUT_CLIENT_NOTIFICATION_SUCCESS';
export const PUT_CLIENT_NOTIFICATION_ERROR = 'PUT_CLIENT_NOTIFICATION_ERROR';

export const GET_VENDOR_CLIENT_COUNT_LOADING = 'GET_VENDOR_CLIENT_COUNT_LOADING';
export const GET_VENDOR_CLIENT_COUNT_SUCCESS = 'GET_VENDOR_CLIENT_COUNT_SUCCESS';
export const GET_VENDOR_CLIENT_COUNT_ERROR = 'GET_VENDOR_CLIENT_COUNT_ERROR';
