export const INIT_STATE = 'INIT_INSIGHT_STATE';

export const GET_SERVICES_LOADING = 'GET_BGV_SERVICES_LOADING';
export const GET_SERVICES_SUCCESS = 'GET_BGV_SERVICES_SUCCESS';
export const GET_SERVICES_ERROR = 'GET_BGV_SERVICES_ERROR';

export const POST_BGV_STATUS_LOADING = 'POST_BGV_STATUS_LOADING';
export const POST_BGV_STATUS_SUCCESS = 'POST_BGV_STATUS_SUCCESS';
export const POST_BGV_STATUS_ERROR = 'POST_BGV_STATUS_ERROR';

export const GET_CUSTOM_BGV_STATUS_LOADING = 'GET_CUSTOM_BGV_STATUS_LOADING';
export const GET_CUSTOM_BGV_STATUS_SUCCESS = 'GET_CUSTOM_BGV_STATUS_SUCCESS';
export const GET_CUSTOM_BGV_STATUS_ERROR = 'GET_CUSTOM_BGV_STATUS_ERROR';