export const INIT_STATE = 'INIT_DATA_STATE';

export const CLEAR_ROLE_TAG_INFO = 'CLEAR_ROLE_TAG_INFO';

export const GET_EMP_DATA_LOADING = 'GET_EMP_DATA_LOADING';
export const GET_EMP_DATA_SUCCESS = 'GET_EMP_DATA_SUCCESS';
export const GET_EMP_DATA_ERROR = 'GET_EMP_DATA_ERROR';

export const GET_ORG_DATA_LOADING = 'GET_ORG_DATA_LOADING';
export const GET_ORG_DATA_SUCCESS = 'GET_ORG_DATA_SUCCESS';
export const GET_ORG_DATA_ERROR = 'GET_ORG_DATA_ERROR';

export const GET_ROLE_TAG_DATA_LOADING = 'GET_ROLE_TAG_DATA_LOADING';
export const GET_ROLE_TAG_DATA_SUCCESS = 'GET_ROLE_TAG_DATA_SUCCESS';
export const GET_ROLE_TAG_DATA_ERROR = 'GET_ROLE_TAG_DATA_ERROR';

export const GET_LOCATION_TAG_DATA_LOADING = 'GET_LOCATION_TAG_DATA_LOADING';
export const GET_LOCATION_TAG_DATA_SUCCESS = 'GET_LOCATION_TAG_DATA_SUCCESS';
export const GET_LOCATION_TAG_DATA_ERROR = 'GET_LOCATION_TAG_DATA_ERROR';

export const DOWNLOAD_ZIP_PDF_LOADING = 'DOWNLOAD_ZIP_PDF_LOADING';
export const DOWNLOAD_ZIP_PDF_SUCCESS = 'DOWNLOAD_ZIP_PDF_SUCCESS';
export const DOWNLOAD_ZIP_PDF_ERROR = 'DOWNLOAD_ZIP_PDF_ERROR';

export const DOWNLOAD_SUMMARY_PDF_LOADING = 'DOWNLOAD_SUMMARY_PDF_LOADING';
export const DOWNLOAD_SUMMARY_PDF_SUCCESS = 'DOWNLOAD_SUMMARY_PDF_SUCCESS';
export const DOWNLOAD_SUMMARY_PDF_ERROR = 'DOWNLOAD_SUMMARY_PDF_ERROR';

export const DOWNLOAD_ATTACHMENT_LOADING = 'DOWNLOAD_ATTACHMENT_LOADING';
export const DOWNLOAD_ATTACHMENT_SUCCESS = 'DOWNLOAD_ATTACHMENT_SUCCESS';
export const DOWNLOAD_ATTACHMENT_ERROR = 'DOWNLOAD_ATTACHMENT_ERROR';
