export const INIT_STATE = 'INIT_EXCEL_STATE';

export const UPLOAD_FILE_LOADING = 'UPLOAD_EXCEL_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_EXCEL_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_EXCEL_FILE_ERROR';

export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
export const SOCKET_CONNECTION_SUCCESS = 'SOCKET_CONNECTION_SUCCESS';

export const SCAN_SOCKET_CONNECTION_CLOSED = 'SCAN_SOCKET_CONNECTION_CLOSED';

export const PROCESS_DATA_STATUS_LOADING = 'PROCESS_DATA_STATUS_LOADING';
export const PROCESS_DATA_STATUS_SUCCESS = 'PROCESS_DATA_STATUS_SUCCESS';
export const PROCESS_DATA_STATUS_ERROR = 'PROCESS_DATA_STATUS_ERROR';

export const PROCESS_SOCKET_CONNECTION_ERROR = 'PROCESS_SOCKET_CONNECTION_ERROR';
export const PROCESS_SOCKET_CONNECTION_SUCCESS = 'PROCESS_SOCKET_CONNECTION_SUCCESS';

export const PROCESS_SOCKET_CONNECTION_CLOSED = 'PROCESS_SOCKET_CONNECTION_CLOSED';

export const BGV_INITIATE_EXCEL_LOADING = 'BGV_INITIATE_EXCEL_LOADING';
export const BGV_INITIATE_EXCEL_SUCCESS = 'BGV_INITIATE_EXCEL_SUCCESS';
export const BGV_INITIATE_EXCEL_ERROR = 'BGV_INITIATE_EXCEL_ERROR';

export const BGV_REINITIATE_EXCEL_LOADING = 'BGV_REINITIATE_EXCEL_LOADING';
export const BGV_REINITIATE_EXCEL_SUCCESS = 'BGV_REINITIATE_EXCEL_SUCCESS';
export const BGV_REINITIATE_EXCEL_ERROR = 'BGV_REINITIATE_EXCEL_ERROR';

export const STOP_PROCESS_LOADING = 'STOP_PROCESS_LOADING';
export const STOP_PROCESS_SUCCESS = 'STOP_PROCESS_SUCCESS';
export const STOP_PROCESS_ERROR = 'STOP_PROCESS_ERROR';

export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';

export const CHECK_EXCEL_STATUS_LOADING = 'CHECK_EXCEL_STATUS_LOADING';
export const CHECK_EXCEL_STATUS_SUCCESS = 'CHECK_EXCEL_STATUS_SUCCESS';
export const CHECK_EXCEL_STATUS_ERROR = 'CHECK_EXCEL_STATUS_ERROR';

export const RESET_EXCEL_DATA = 'RESET_EXCEL_DATA';

// export const DOWNLOAD_ERROR_EXCEL_STATUS_LOADING = 'DOWNLOAD_ERROR_EXCEL_STATUS_LOADING';
// export const DOWNLOAD_ERROR_EXCEL_STATUS_SUCCESS = 'DOWNLOAD_ERROR_EXCEL_STATUS_SUCCESS';
// export const DOWNLOAD_ERROR_EXCEL_STATUS_ERROR = 'DOWNLOAD_ERROR_EXCEL_STATUS_ERROR';

export const DOWNLOAD_ERROR_EXCEL_LOADING = 'DOWNLOAD_ERROR_EXCEL_LOADING';
export const DOWNLOAD_ERROR_EXCEL_SUCCESS = 'DOWNLOAD_ERROR_EXCEL_SUCCESS';
export const DOWNLOAD_ERROR_EXCEL_ERROR = 'DOWNLOAD_ERROR_EXCEL_ERROR';

export const GET_TAG_NAME_LOADING = 'GET_TAG_NAME_LOADING';
export const GET_TAG_NAME_SUCCESS = 'GET_TAG_NAME_SUCCESS';
export const GET_TAG_NAME_ERROR = 'GET_TAG_NAME_ERROR';

export const CHANGE_STATUS_LOADING = 'CHANGE_STATUS_LOADING';
export const CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS';
export const CHANGE_STATUS_ERROR = 'CHANGE_STATUS_ERROR';