export const INIT_STATE = 'INIT_ORG_MGMT_STATE';
export const GET_DATA_LIST_LOADING = 'GET_ORG_STATIC_DATA_LOADING';
export const GET_DATA_LIST_SUCCESS = 'GET_ORG_STATIC_DATA_SUCCESS';
export const GET_DATA_LIST_ERROR = 'GET_ORG_STATIC_DATA_ERROR';

export const GET_DATA_LOADING = 'GET_DETAILS_LOADING';
export const GET_DATA_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DATA_ERROR = 'GET_DETAILS_ERROR';

export const GET_SERVICES_ENABLED_LOADING = 'ORG_MGMT_GET_SERVICES_ENABLED_LOADING';
export const GET_SERVICES_ENABLED_SUCCESS = 'ORG_MGMT_GET_SERVICES_ENABLED_SUCCESS';
export const GET_SERVICES_ENABLED_ERROR = 'ORG_MGMT_GET_SERVICES_ENABLED_ERROR';
