export const initFilterElements = ['male', 'female', 'other', 'employee', 'tenant', 'business associate', 'active', 'inactive terminated',
  'full-time', 'part-time', 'contractor', 'hired', 'pre-hired', 'terminated',
  'notified superiors', 'absconded', 'assigned', 'not assigned', 'direct reportee',
  'red', 'yellow', 'green', 'not initiated', 'in progress', 'missing information', 'insufficient information',
  'from', 'to', 'createdFrom', 'createdTo', 'migrated', 'local', 'basic registration completed', 'additional data added', 'employment details added',
  'company documents generated', 'government documents generated', 'additional details', 'employment details',
  'company documents', 'government documents', 'terminatedFromDate', 'terminatedToDate',
];

export const filterURLValue = {
  male: 'MALE',
  female: 'FEMALE',
  other: 'OTHER',
  employee: 'EMPLOYEE',
  tenant: 'TENANT',
  'business associate': 'BUSINESS_ASSOCIATE',
  active: 'true',
  inactive: 'false',
  fullTime: 'FULL_TIME',
  partTime: 'PART_TIME',
  contractor: 'CONTRACTOR',
  hired: 'HIRED',
  preHired: 'PRE_HIRED',
  terminated: 'TERMINATED',
  notifiedSuperiors: 'NOTIFIED_SUPERIORS',
  absconded: 'ABSCONDED',
  gotTerminated: 'TERMINATED',
  directReportee: 'me',
  migrated: 'MIGRATED',
  local: 'LOCAL',
  red: 'RED',
  yellow: 'YELLOW',
  green: 'GREEN',
  notInitiated: 'NOT_INITIATED',
  inProgress: 'inProgress',
  missing_info: 'missing_info',
  insufficient_info: 'insufficient_info',
  assigned: 'true',
  notAssigned: 'false',
};
