export const INIT_STATE = 'INIT_EDUCATION_STATE';

export const GET_DOCUMENTS_LOADING = 'GET_DOCUMENTS_LOADING';
export const GET_DOCUMENTS_ERROR = 'GET_DOCUMENTS_ERROR';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';

// export const GET_AGENCY_TASKS_COUNT_LOADING = 'GET_AGENCY_TASKS_COUNT_LOADING';
// export const GET_AGENCY_TASKS_COUNT_SUCCESS = 'GET_AGENCY_TASKS_COUNT_SUCCESS';
// export const GET_AGENCY_TASKS_COUNT_ERROR = 'GET_AGENCY_TASKS_COUNT_ERROR';

export const GET_POSTAL_COUNT_LOADING = 'GET_POSTAL_COUNT_LOADING';
export const GET_POSTAL_COUNT_SUCCESS = 'GET_POSTAL_COUNT_SUCCESS';
export const GET_POSTAL_COUNT_ERROR = 'GET_POSTAL_COUNT_ERROR';

export const GET_PHYSICAL_COUNT_LOADING = 'GET_PHYSICAL_COUNT_LOADING';
export const GET_PHYSICAL_COUNT_SUCCESS = 'GET_PHYSICAL_COUNT_SUCCESS';
export const GET_PHYSICAL_COUNT_ERROR = 'GET_PHYSICAL_COUNT_ERROR';