export const INIT_STATE = 'SITE_CONFIG_INIT_STATE';

export const POST_ATTEND_SITE_CONFIG_LOADING = 'POST_ATTEND_SITE_CONFIG_LOADING';
export const POST_ATTEND_SITE_CONFIG_SUCCESS = 'POST_ATTEND_SITE_CONFIG_SUCCESS';
export const POST_ATTEND_SITE_CONFIG_ERROR = 'POST_ATTEND_SITE_CONFIG_ERROR';

export const PUT_ATTEND_SITE_CONFIG_LOADING = 'PUT_ATTEND_SITE_CONFIG_LOADING';
export const PUT_ATTEND_SITE_CONFIG_SUCCESS = 'PUT_ATTEND_SITE_CONFIG_SUCCESS';
export const PUT_ATTEND_SITE_CONFIG_ERROR = 'PUT_ATTEND_SITE_CONFIG_ERROR';

export const GET_ATTEND_SITE_CONFIG_LOADING = 'GET_ATTEND_SITE_CONFIG_LOADING';
export const GET_ATTEND_SITE_CONFIG_SUCCESS = 'GET_ATTEND_SITE_CONFIG_SUCCESS';
export const GET_ATTEND_SITE_CONFIG_ERROR = 'GET_ATTEND_SITE_CONFIG_ERROR';

export const DELETE_ATTEND_SITE_CONFIG_LOADING = 'DELETE_ATTEND_SITE_CONFIG_LOADING';
export const DELETE_ATTEND_SITE_CONFIG_SUCCESS = 'DELETE_ATTEND_SITE_CONFIG_SUCCESS';
export const DELETE_ATTEND_SITE_CONFIG_ERROR = 'DELETE_ATTEND_SITE_CONFIG_ERROR';

export const GET_ATTEND_SITE_CONFIG_COUNT_LOADING = 'GET_ATTEND_SITE_CONFIG_COUNT_LOADING';
export const GET_ATTEND_SITE_CONFIG_COUNT_SUCCESS = 'GET_ATTEND_SITE_CONFIG_COUNT_SUCCESS';
export const GET_ATTEND_SITE_CONFIG_COUNT_ERROR = 'GET_ATTEND_SITE_CONFIG_COUNT_ERROR';

export const GET_ATTEND_SITE_CONFIG_LIST_LOADING = 'GET_ATTEND_SITE_CONFIG_LIST_LOADING';
export const GET_ATTEND_SITE_CONFIG_LIST_SUCCESS = 'GET_ATTEND_SITE_CONFIG_LIST_SUCCESS';
export const GET_ATTEND_SITE_CONFIG_LIST_ERROR = 'GET_ATTEND_SITE_CONFIG_LIST_ERROR';

export const POST_TAG_INFO_DATA_LOADING = 'POST_TAG_INFO_DATA_LOADING';
export const POST_TAG_INFO_DATA_SUCCESS = 'POST_TAG_INFO_DATA_SUCCESS';
export const POST_TAG_INFO_DATA_ERROR = 'POST_TAG_INFO_DATA_ERROR';
