export const GET_INIT_STATE = 'GET_INIT_STATE';

export const GET_BPCONTACT_LIST_LOADING = 'GET_CONTACT_LIST_LOADING';
export const GET_BPCONTACT_LIST_SUCCESS = 'GET_BPCONTACT_LIST_SUCCESS';
export const GET_BPCONTACT_LIST_ERROR = 'GET_BPCONTACT_LIST_ERROR';

export const POST_ATTEND_BP_SPOCS_LOADING = 'POST_ATTEND_BP_SPOCS_LOADING';
export const POST_ATTEND_BP_SPOCS_SUCCESS = 'POST_ATTEND_BP_SPOCS_SUCCESS';
export const POST_ATTEND_BP_SPOCS_ERROR = 'POST_ATTEND_BP_SPOCS_ERROR';

export const GET_ATTEND_BP_SPOCS_LOADING = 'GET_ATTEND_BP_SPOCS_LOADING';
export const GET_ATTEND_BP_SPOCS_SUCCESS = 'GET_ATTEND_BP_SPOCS_SUCCESS';
export const GET_ATTEND_BP_SPOCS_ERROR = 'GET_BPSELECTED_SPOCS_ERROR';

export const GET_BPEMP_LOADING = 'GET_BPEMP_LOADING';
export const GET_BPEMP_SUCCESS = 'GET_BPEMP_SUCCESS';
export const GET_BPEMP_ERROR = 'GET_BPEMP_ERROR';

export const GET_TAG_NAME_LOADING = 'GET_TAG_NAME_SPOC_LOADING';
export const GET_TAG_NAME_SUCCESS = 'GET_TAG_NAME_SPOC_SUCCESS';
export const GET_TAG_NAME_ERROR = 'GET_TAG_NAME_SPOC_ERROR';

export const GET_BPEMP_DATA_LOADING = 'GET_BPEMP_ATTEND_DATA_LOADING';
export const GET_BPEMP_DATA_SUCCESS = 'GET_BPEMP_ATTEND_DATA_SUCCESS';
export const GET_BPEMP_DATA_ERROR = 'GET_BPEMP_ATTEND_DATA_ERROR';
