export const INIT_STATE = 'INIT_PROFILE_STATE';

export const GET_EMP_DATA_LOADING = 'GET_PROFILE_EMP_DATA_LOADING_PROFILE';
export const GET_EMP_DATA_SUCCESS = 'GET_PROFILE_EMP_DATA_SUCCESS_PROFILE';
export const GET_EMP_DATA_ERROR = 'GET_PROFILE_EMP_DATA_ERROR_PROFILE';

export const GET_EMP_BGV_DATA_LOADING = 'GET_EMP_BGV_DATA_LOADING';
export const GET_EMP_BGV_DATA_SUCCESS = 'GET_EMP_BGV_DATA_SUCCESS';
export const GET_EMP_BGV_DATA_ERROR = 'GET_EMP_BGV_DATA_ERROR';

export const GET_EMP_MISSING_DATA_LOADING = 'GET_EMP_MISSING_DATA_LOADING';
export const GET_EMP_MISSING_DATA_SUCCESS = 'GET_EMP_MISSING_DATA_SUCCESS';
export const GET_EMP_MISSING_DATA_ERROR = 'GET_EMP_MISSING_DATA_ERROR';

export const GET_TAG_NAME_LOADING = 'GET_TAG_NAME_LOADING';
export const GET_TAG_NAME_SUCCESS = 'GET_TAG_NAME_SUCCESS';
export const GET_TAG_NAME_ERROR = 'GET_TAG_NAME_ERROR';

export const DOWNLOAD_FILE_LOADING = 'DOWNLOAD_DOCUMENT_FILE_LOADING';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_DOCUMENT_FILE_SUCCESS';
export const DOWNLOAD_FILE_ERROR = 'DOWNLOAD_DOCUMENT_FILE_ERROR';

export const GET_VENDOR_CLIENT_INFO_LOADING = 'GET_VENDOR_CLIENT_INFO_LOADING';
export const GET_VENDOR_CLIENT_INFO_SUCCESS = 'GET_VENDOR_CLIENT_INFO_SUCCESS';
export const GET_VENDOR_CLIENT_INFO_ERROR = 'GET_VENDOR_CLIENT_INFO_ERROR';

export const GET_EMP_LEAVE_QUOTA_LOADING = 'GET_EMP_LEAVE_QUOTA_LOADING';
export const GET_EMP_LEAVE_QUOTA_SUCCESS = 'GET_EMP_LEAVE_QUOTA_SUCCESS';
export const GET_EMP_LEAVE_QUOTA_ERROR = 'GET_EMP_LEAVE_QUOTA_ERROR';

export const GET_ORG_LIST_INFO_LOADING = 'GET_ORG_LIST_INFO_LOADING';
export const GET_ORG_LIST_INFO_SUCCESS = 'GET_ORG_LIST_INFO_SUCCESS';
export const GET_ORG_LIST_INFO_ERROR = 'GET_ORG_LIST_INFO_ERROR';
