export const INIT_STATE = 'SHIFT_DETAILS_INIT';

export const POST_SHIFT_DETAILS_BY_ID_LOADING = 'POST_SHIFT_DETAILS_BY_ID_LOADING';
export const POST_SHIFT_DETAILS_BY_ID_SUCCESS = 'POST_SHIFT_DETAILS_BY_ID_SUCCESS';
export const POST_SHIFT_DETAILS_BY_ID_ERROR = 'POST_SHIFT_DETAILS_BY_ID_ERROR';

export const GET_SHIFT_DETAILS_BY_ID_LOADING = 'GET_SHIFT_DETAILS_BY_ID_LOADING';
export const GET_SHIFT_DETAILS_BY_ID_SUCCESS = 'GET_SHIFT_DETAILS_BY_ID_SUCCESS';
export const GET_SHIFT_DETAILS_BY_ID_ERROR = 'GET_SHIFT_DETAILS_BY_ID_ERROR';

export const PUT_SHIFT_DETAILS_BY_ID_LOADING = 'PUT_SHIFT_DETAILS_BY_ID_LOADING';
export const PUT_SHIFT_DETAILS_BY_ID_SUCCESS = 'PUT_SHIFT_DETAILS_BY_ID_SUCCESS';
export const PUT_SHIFT_DETAILS_BY_ID_ERROR = 'PUT_SHIFT_DETAILS_BY_ID_ERROR';

export const DELETE_SHIFT_DETAILS_BY_ID_LOADING = 'DELETE_SHIFT_DETAILS_BY_ID_LOADING';
export const DELETE_SHIFT_DETAILS_BY_ID_SUCCESS = 'DELETE_SHIFT_DETAILS_BY_ID_SUCCESS';
export const DELETE_SHIFT_DETAILS_BY_ID_ERROR = 'DELETE_SHIFT_DETAILS_BY_ID_ERROR';
