export const GET_FILTER_TAG_MAP_LIST_LOADING = 'GET_FILTER_TAG_MAP_LIST_LOADING';
export const GET_FILTER_TAG_MAP_LIST_SUCCESS = 'GET_FILTER_TAG_MAP_LIST_SUCCESS';
export const GET_FILTER_TAG_MAP_LIST_ERROR = 'GET_FILTER_TAG_MAP_LIST_ERROR';
