export const INIT_STATE = 'HOLIDAY_CONFIG_INIT_STATE';

export const POST_HOLIDAY_CONFIGURATION_LOADING = 'POST_HOLIDAY_CONGIGURATION_LOADING';
export const POST_HOLIDAY_CONFIGURATION_SUCCESS = 'POST_HOLIDAY_CONGIGURATION_SUCCESS';
export const POST_HOLIDAY_CONFIGURATION_ERROR = 'POST_HOLIDAY_CONGIGURATION_ERROR';

export const PUT_HOLIDAY_CONFIGURATION_LOADING = 'PUT_HOLIDAY_CONGIGURATION_LOADING';
export const PUT_HOLIDAY_CONFIGURATION_SUCCESS = 'PUT_HOLIDAY_CONGIGURATION_SUCCESS';
export const PUT_HOLIDAY_CONFIGURATION_ERROR = 'PUT_HOLIDAY_CONGIGURATION_ERROR';

export const DELETE_HOLIDAY_CONFIGURATION_LOADING = 'DELETE_HOLIDAY_CONGIGURATION_LOADING';
export const DELETE_HOLIDAY_CONFIGURATION_SUCCESS = 'DELETE_HOLIDAY_CONGIGURATION_SUCCESS';
export const DELETE_HOLIDAY_CONFIGURATION_ERROR = 'DELETE_HOLIDAY_CONGIGURATION_ERROR';

export const GET_HOLIDAY_CONFIGURATION_LOADING = 'GET_HOLIDAY_CONGIGURATION_LOADING';
export const GET_HOLIDAY_CONFIGURATION_SUCCESS = 'GET_HOLIDAY_CONGIGURATION_SUCCESS';
export const GET_HOLIDAY_CONFIGURATION_ERROR = 'GET_HOLIDAY_CONGIGURATION_ERROR';

export const GET_HOLIDAY_CONFIGURATION_BY_ID_LOADING = 'GET_HOLIDAY_CONGIGURATION_BY_ID_LOADING';
export const GET_HOLIDAY_CONFIGURATION_BY_ID_SUCCESS = 'GET_HOLIDAY_CONGIGURATION_BY_ID_SUCCESS';
export const GET_HOLIDAY_CONFIGURATION_BY_ID_ERROR = 'GET_HOLIDAY_CONGIGURATION_BY_ID_ERROR';

export const GET_TAG_INFO_LOADING = 'GET_TAG_INFO_HOLIDAY_CONFIG_LOADING';
export const GET_TAG_INFO_SUCCESS = 'GET_TAG_INFO_HOLIDAY_CONFIG_SUCCESS';
export const GET_TAG_INFO_ERROR = 'GET_TAG_INFO_HOLIDAY_CONFIG_ERROR';
