export const ORG_SET_ID_DATA='ORG_SET_ID_DATA';
export const ORG_RESET_ID_DATA='ORG_RESET_ID_DATA';

export const GET_INIT_STATE='GET_INIT_STATE';

export const ORG_CHECK_LOADING = 'ORG_CHECK_LOADING';
export const ORG_CHECK_SUCCESS = 'ORG_CHECK_SUCCESS';
export const ORG_CHECK_ERROR = 'ORG_CHECK_ERROR';
