export const UPLOAD_ORG_ONBOARD_DOCUMENT_LOADING='UPLOAD_ORG_ONBOARD_DOCUMENT_LOADING';
export const UPLOAD_ORG_ONBOARD_DOCUMENT_SUCCESS='UPLOAD_ORG_ONBOARD_DOCUMENT_SUCCESS';
export const UPLOAD_ORG_ONBOARD_DOCUMENT_ERROR='UPLOAD_ORG_ONBOARD_DOCUMENT_ERROR';

export const FILE_PROCESS_LOADING = "ORG_ONBOARD_FILE_PROCESS_LOADING";
export const FILE_PROCESS_SUCCESS = "ORG_ONBOARD_FILE_PROCESS_SUCCESS";
export const FILE_PROCESS_ERROR = "ORG_ONBOARD_FILE_PROCESS_ERROR";

export const DOWNLOAD_ORG_ONBOARD_FILE_LOADING = "ORG_ONBOARD_FILE_DOWNLOAD_LOADING";
export const DOWNLOAD_ORG_ONBOARD_FILE_SUCCESS = "ORG_ONBOARD_FILE_DOWNLOAD_SUCCESS";
export const DOWNLOAD_ORG_ONBOARD_FILE_ERROR = "ORG_ONBOARD_FILE_DOWNLOAD_ERROR";

export const INIT_STATE = "ORG_ONBOARD_DOCUMENT_MGMT_INIT";

export const SET_CURRENT_DOCUMENT = "ORG_ONBOARD_SET_CURRENT_DOCUMENT";
export const RESET_CURRENT_DOCUMENT = "ORG_ONBOARD_RESET_CURRENT_DOCUMENT";

export const DOWNLOAD_FILE_LOADING = "ORG_ONBOARD_DOWNLOAD_FILE_LOADING";
export const DOWNLOAD_FILE_SUCCESS = "ORG_ONBOARD_DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_ERROR = "ORG_ONBOARD_DOWNLOAD_FILE_ERROR";

export const DOWNLOAD_TEMPLATE_FILE_LOADING = "ORG_ONBOARD_DOWNLOAD_TEMPLATE_FILE_LOADING";
export const DOWNLOAD_TEMPLATE_FILE_SUCCESS = "ORG_ONBOARD_DOWNLOAD_TEMPLATE_FILE_SUCCESS";
export const DOWNLOAD_TEMPLATE_FILE_ERROR = "ORG_ONBOARD_DOWNLOAD_TEMPLATE_FILE_ERROR";

export const POST_ORG_ONBOARD_CONFIG_LOADING = "POST_ORG_ONBOARD_DOCUMENT_CONFIG_LOADING"
export const POST_ORG_ONBOARD_CONFIG_SUCCESS = "POST_ORG_ONBOARD_DOCUMENT_CONFIG_SUCCESS"
export const POST_ORG_ONBOARD_CONFIG_ERROR = "POST_ORG_ONBOARD_DOCUMENT_CONFIG_ERROR"


export const UPDATE_SECTION_STATUS = 'UPDATE_EMPLOYEE_DOCUMENT_SECTION_STATUS';