export const INIT_STATE = 'INIT_PHYSICAL_ADDRESS_VERIFICATION_STATE';

export const GET_TASK_CLOSURE_STATIC_DATA_LOADING = 'GET_TASK_CLOSURE_STATIC_DATA_LOADING';
export const GET_TASK_CLOSURE_STATIC_DATA_SUCCESS = 'GET_TASK_CLOSURE_STATIC_DATA_SUCCESS';
export const GET_TASK_CLOSURE_STATIC_DATA_ERROR = 'GET_TASK_CLOSURE_STATIC_DATA_ERROR';

export const GET_INDIVIDUAL_TASK_LOADING = 'GET_INDIVIDUAL_TASK_LOADING';
export const GET_INDIVIDUAL_TASK_SUCCESS = 'GET_INDIVIDUAL_TASK_SUCCESS';
export const GET_INDIVIDUAL_TASK_ERROR = 'GET_INDIVIDUAL_TASK_ERROR';

export const GET_TAG_NAME_LOADING = 'GET_TAG_NAME_SPOC_LOADING';
export const GET_TAG_NAME_SUCCESS = 'GET_TAG_NAME_SPOC_SUCCESS';
export const GET_TAG_NAME_ERROR = 'GET_TAG_NAME_SPOC_ERROR';

export const POST_INDIVIDUAL_TASK_LOADING = 'POST_INDIVIDUAL_TASK_LOADING';
export const POST_INDIVIDUAL_TASK_SUCCESS = 'POST_INDIVIDUAL_TASK_SUCCESS';
export const POST_INDIVIDUAL_TASK_ERROR = 'POST_INDIVIDUAL_TASK_ERROR';

export const GET_INDIVIDUAL_TASK_NOTIFICATION = 'GET_INDIVIDUAL_TASK_NOTIFICATION';

export const GET_ADDRESS_PIC_LOADING = 'GET_PHYSICAL_ADDRESS_PIC_LOADING';
export const GET_ADDRESS_PIC_SUCCESS = 'GET_PHYSICAL_ADDRESS_PIC_SUCCESS';
export const GET_ADDRESS_PIC_ERROR = 'GET_PHYSICAL_ADDRESS_PIC_ERROR';

export const UPLOAD_PHYSICAL_ADDRESS_LOADING = 'ADD_PHYSICAL_ADDRESS_URL_LOADING';
export const UPLOAD_PHYSICAL_ADDRESS_SUCCESS = 'ADD_PHYSICAL_ADDRESS_URL_SUCCESS';
export const UPLOAD_PHYSICAL_ADDRESS_ERROR = 'ADD_PHYSICAL_ADDRESS_URL_ERROR';

export const DELETE_PHYSICAL_ADDRESS_LOADING = 'DELETE_PHYSICAL_ADDRESS_URL_LOADING';
export const DELETE_PHYSICAL_ADDRESS_SUCCESS = 'DELETE_PHYSICAL_ADDRESS_URL_SUCCESS';
export const DELETE_PHYSICAL_ADDRESS_ERROR = 'DELETE_PHYSICAL_ADDRESS_URL_ERROR';

export const GET_ADDRESS_IMAGES_INTI_STATE = 'GET_ADDRESS_IMAGES_INTIAL_STATE';