export const INIT_VENDOR_MGMT_STATE = 'INIT_VENDOR_MGMT_STATE';

export const GET_VENDOR_STATIC_DATA_LOADING = 'GET_VENDOR_STATIC_DATA_LOADING';
export const GET_VENDOR_STATIC_DATA_SUCCESS = 'GET_VENDOR_STATIC_DATA_SUCCESS';
export const GET_VENDOR_STATIC_DATA_ERROR = 'GET_VENDOR_STATIC_DATA_ERROR';
