export const INIT_VENDOR_TAGS_STATE = 'INIT_VENDOR_TAGS_STATE';

export const POST_ASSIGN_VENDOR_TAGS_LOADING = 'POST_ASSIGN_VENDOR_TAGS_LOADING';
export const POST_ASSIGN_VENDOR_TAGS_SUCCESS = 'POST_ASSIGN_VENDOR_TAGS_SUCCESS';
export const POST_ASSIGN_VENDOR_TAGS_ERROR = 'POST_ASSIGN_VENDOR_TAGS_ERROR';
