export const GET_VENDOR_DATA_BY_ID_LOADING = 'GET_VENDOR_DATA_BY_ID_LOADING';
export const GET_VENDOR_DATA_BY_ID_SUCCESS = 'GET_VENDOR_DATA_BY_ID_SUCCESS';
export const GET_VENDOR_DATA_BY_ID_ERROR = 'GET_VENDOR_DATA_BY_ID_ERROR';

export const GET_CLIENT_NOTIFICATION_LOADING = 'GET_CLIENT_NOTIFICATION_LOADING';
export const GET_CLIENT_NOTIFICATION_SUCCESS = 'GET_CLIENT_NOTIFICATION_SUCCESS';
export const GET_CLIENT_NOTIFICATION_ERROR = 'GET_CLIENT_NOTIFICATION_ERROR';

export const PUT_CLIENT_NOTIFICATION_LOADING = 'PUT_CLIENT_NOTIFICATION_LOADING';
export const PUT_CLIENT_NOTIFICATION_SUCCESS = 'PUT_CLIENT_NOTIFICATION_SUCCESS';
export const PUT_CLIENT_NOTIFICATION_ERROR = 'PUT_CLIENT_NOTIFICATION_ERROR';

export const GET_CLIENT_DATA_BY_ID_LOADING = 'GET_CLIENT_DATA_BY_ID_LOADING';
export const GET_CLIENT_DATA_BY_ID_SUCCESS = 'GET_CLIENT_DATA_BY_ID_SUCCESS';
export const GET_CLIENT_DATA_BY_ID_ERROR = 'GET_CLIENT_DATA_BY_ID_ERROR';
