export const INIT_STATE = 'INIT_EMP_SIGNATURE_STATE';

export const DOWNLOAD_SIGNATURE_LOADING = "EMPLOYEE_DOWNLOAD_SIGNATURE_LOADING";
export const DOWNLOAD_SIGNATURE_SUCCESS = "EMPLOYEE_DOWNLOAD_SIGNATURE_SUCCESS";
export const DOWNLOAD_SIGNATURE_ERROR = "EMPLOYEE_DOWNLOAD_SIGNATURE_ERROR";

export const UPLOAD_SIGNATURE_LOADING = "EMPLOYEE_UPLOAD_SIGNATURE_LOADING";
export const UPLOAD_SIGNATURE_SUCCESS = "EMPLOYEE_UPLOAD_SIGNATURE_SUCCESS";
export const UPLOAD_SIGNATURE_ERROR = "EMPLOYEE_UPLOAD_SIGNATURE_ERROR";