export const GET_ATTEND_SITE_CONFIG_LOADING = 'GET_ATTEND_SITE_CONFIG_DETAILS_LOADING';
export const GET_ATTEND_SITE_CONFIG_SUCCESS = 'GET_ATTEND_SITE_CONFIG_DETAILS_SUCCESS';
export const GET_ATTEND_SITE_CONFIG_ERROR = 'GET_ATTEND_SITE_CONFIG_DETAILS_ERROR';

export const GET_SITE_SHIFT_LIST_LOADING = 'GET_SITE_SHIFT_LIST_LOADING';
export const GET_SITE_SHIFT_LIST_SUCCESS = 'GET_SITE_SHIFT_LIST_SUCCESS';
export const GET_SITE_SHIFT_LIST_ERROR = 'GET_SITE_SHIFT_LIST_ERROR';

export const GET_TAG_INFO_DATA_LOADING = 'GET_SITE_TAG_INFO_DATA_LOADING';
export const GET_TAG_INFO_DATA_SUCCESS = 'GET_SITE_TAG_INFO_DATA_SUCCESS';
export const GET_TAG_INFO_DATA_ERROR = 'GET_SITE_TAG_INFO_DATA_ERROR';
