

export const GET_ORG_ONBOARD_CONFIG_LOADING = "GET_ORG_ONBOARD_CONFIG_LOADING"
export const GET_ORG_ONBOARD_CONFIG_SUCCESS = "GET_ORG_ONBOARD_CONFIG_SUCCESS"
export const GET_ORG_ONBOARD_CONFIG_ERROR = "GET_ORG_ONBOARD_CONFIG_ERROR"

export const POST_ORG_ONBOARD_CONFIG_LOADING = "POST_ORG_ONBOARD_CONFIG_LOADING"
export const POST_ORG_ONBOARD_CONFIG_SUCCESS = "POST_ORG_ONBOARD_CONFIG_SUCCESS"
export const POST_ORG_ONBOARD_CONFIG_ERROR = "POST_ORG_ONBOARD_CONFIG_ERROR"

export const INIT_STATE = "ORG_ONBOARD_INIT_STATE"

export const UPDATE_SECTION_STATUS = 'UPDATE_ONBOARD_CONFIG_SECTION_STATUS';


// export const UPLOAD_ORG_ONBOARD_DOCUMENT_LOADING='UPLOAD_ORG_ONBOARD_DOCUMENT_LOADING';
// export const UPLOAD_ORG_ONBOARD_DOCUMENT_SUCCESS='UPLOAD_ORG_ONBOARD_DOCUMENT_SUCCESS';
// export const UPLOAD_ORG_ONBOARD_DOCUMENT_ERROR='UPLOAD_ORG_ONBOARD_DOCUMENT_ERROR';

// export const FILE_PROCESS_LOADING = "ORG_ONBOARD_FILE_PROCESS_LOADING";
// export const FILE_PROCESS_SUCCESS = "ORG_ONBOARD_FILE_PROCESS_SUCCESS";
// export const FILE_PROCESS_ERROR = "ORG_ONBOARD_FILE_PROCESS_ERROR";

export const GET_DOCUMENT_LIST_LOADING = 'GET_DOCUMENT_LIST_LOADING';
export const GET_DOCUMENT_LIST_SUCCESS = 'GET_DOCUMENT_LIST_SUCCESS';
export const GET_DOCUMENT_LIST_ERROR = 'GET_DOCUMENT_LIST_ERROR';
