export const INIT_STATE = 'INIT_EMP_EDUCATION_STATE';

export const UPLOAD_FILE_LOADING = 'UPLOAD_EMP_EDUCATION_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_EMP_EDUCATION_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_EMP_EDUCATION_FILE_ERROR';

export const DOWNLOAD_FILE_LOADING = 'DOWNLOAD_EMP_EDUCATION_FILE_LOADING';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_EMP_EDUCATION_FILE_SUCCESS';
export const DOWNLOAD_FILE_ERROR = 'DOWNLOAD_EMP_EDUCATION_FILE_ERROR';