export const INIT_STATE = 'INIT_NOTIFICATION_STATE';

export const GET_NOTIFICATION_LIST_LOADING = 'GET_NOTIFICATION_LIST_LOADING';
export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS';
export const GET_NOTIFICATION_LIST_ERROR = 'GET_NOTIFICATION_LIST_ERROR';

export const NOTIFICATION_CLOSE_LOADING = 'NOTIFICATION_CLOSE_LOADING';
export const NOTIFICATION_CLOSE_SUCCESS = 'NOTIFICATION_CLOSE_SUCCESS';
export const NOTIFICATION_CLOSE_ERROR = 'NOTIFICATION_CLOSE_ERROR';

export const NOTIFICATION_DOWNLOAD_CUST_MGMT_FILE_LOADING = 'NOTIFICATION_DOWNLOAD_CUST_MGMT_FILE_LOADING';
export const NOTIFICATION_DOWNLOAD_CUST_MGMT_FILE_SUCCESS = 'NOTIFICATION_DOWNLOAD_CUST_MGMT_FILE_SUCCESS';
export const NOTIFICATION_DOWNLOAD_CUST_MGMT_FILE_ERROR = 'NOTIFICATION_DOWNLOAD_CUST_MGMT_FILE_ERROR';

export const NOTIFICATION_DOWNLOAD_BGV_REPORT_FILE_LOADING = 'NOTIFICATION_DOWNLOAD_BGV_REPORT_FILE_LOADING';
export const NOTIFICATION_DOWNLOAD_BGV_REPORT_FILE_SUCCESS = 'NOTIFICATION_DOWNLOAD_BGV_REPORT_FILE_SUCCESS';
export const NOTIFICATION_DOWNLOAD_BGV_REPORT_FILE_ERROR = 'NOTIFICATION_DOWNLOAD_BGV_REPORT_FILE_ERROR';

export const POST_REINITIATE_ALL_LOADING = 'NOTIFICATION_REINITIATE_BGV_LOADING';
export const POST_REINITIATE_ALL_SUCCESS = 'NOTIFICATION_REINITIATE_BGV_SUCCESS';
export const POST_REINITIATE_ALL_ERROR = 'NOTIFICATION_REINITIATE_BGV_ERROR';

export const DOWNLOAD_REINITIATE_LIST_LOADING = 'NOTIFICATION_DOWNLOAD_REINITIATE_LIST_LOADING';
export const DOWNLOAD_REINITIATE_LIST_SUCCESS = 'NOTIFICATION_DOWNLOAD_REINITIATE_LIST_SUCCESS';
export const DOWNLOAD_REINITIATE_LIST_ERROR = 'NOTIFICATION_DOWNLOAD_REINITIATE_LIST_ERROR';

export const UPDATE_VENDOR_APPROVAL_REQ_LOADING = 'UPDATE_VENDOR_APPROVAL_REQ_LOADING';
export const UPDATE_VENDOR_APPROVAL_REQ_SUCCESS = 'UPDATE_VENDOR_APPROVAL_REQ_SUCCESS';
export const UPDATE_VENDOR_APPROVAL_REQ_ERROR = 'UPDATE_VENDOR_APPROVAL_REQ_ERROR';
