export const GET_INIT_STATE = 'SEARCH_EMPLOYEE_INIT_STATE';

export const SEARCH_EMPLOYEE_LOADING = 'SEARCH_EMPLOYEE_COMPONENT_LOADING';
export const SEARCH_EMPLOYEE_SUCCESS = 'SEARCH_EMPLOYEE_COMPONENT_SUCCESS';
export const SEARCH_EMPLOYEE_ERROR = 'SEARCH_EMPLOYEE_COMPONENT_ERROR';