export const INIT_VENDOR_PROFILE_STATE = 'INIT_VENDOR_PROFILE_STATE';

export const GET_VENDOR_OVERALL_INSIGHTS_LOADING = 'GET_VENDOR_OVERALL_INSIGHTS_LOADING';
export const GET_VENDOR_OVERALL_INSIGHTS_SUCCESS = 'GET_VENDOR_OVERALL_INSIGHTS_SUCCESS';
export const GET_VENDOR_OVERALL_INSIGHTS_ERROR = 'GET_VENDOR_OVERALL_INSIGHTS_ERROR';

export const GET_VENDOR_ASSIGNED_CLIENTS_COUNT_LOADING = 'GET_VENDOR_ASSIGNED_CLIENTS_COUNT_LOADING';
export const GET_VENDOR_ASSIGNED_CLIENTS_COUNT_SUCCESS = 'GET_VENDOR_ASSIGNED_CLIENTS_COUNT_SUCCESS';
export const GET_VENDOR_ASSIGNED_CLIENTS_COUNT_ERROR = 'GET_VENDOR_ASSIGNED_CLIENTS_COUNT_ERROR';

export const GET_VENDOR_ASSIGNED_CLIENTS_LOADING = 'GET_VENDOR_ASSIGNED_CLIENTS_LOADING';
export const GET_VENDOR_ASSIGNED_CLIENTS_SUCCESS = 'GET_VENDOR_ASSIGNED_CLIENTS_SUCCESS';
export const GET_VENDOR_ASSIGNED_CLIENTS_ERROR = 'GET_VENDOR_ASSIGNED_CLIENTS_ERROR';

export const GET_ASSOCIATED_VENDORS_COUNT_LOADING = 'GET_ASSOCIATED_VENDORS_COUNT_LOADING';
export const GET_ASSOCIATED_VENDORS_COUNT_SUCCESS = 'GET_ASSOCIATED_VENDORS_COUNT_SUCCESS';
export const GET_ASSOCIATED_VENDORS_COUNT_ERROR = 'GET_ASSOCIATED_VENDORS_COUNT_ERROR';

export const GET_ASSOCIATED_VENDORS_LOADING = 'GET_ASSOCIATED_VENDORS_LOADING';
export const GET_ASSOCIATED_VENDORS_SUCCESS = 'GET_ASSOCIATED_VENDORS_SUCCESS';
export const GET_ASSOCIATED_VENDORS_ERROR = 'GET_ASSOCIATED_VENDORS_ERROR';

// export const GET_VENDOR_DATA_BY_ID_LOADING = 'GET_VENDOR_DATA_BY_ID_LOADING';
// export const GET_VENDOR_DATA_BY_ID_SUCCESS = 'GET_VENDOR_DATA_BY_ID_SUCCESS';
// export const GET_VENDOR_DATA_BY_ID_ERROR = 'GET_VENDOR_DATA_BY_ID_ERROR';
