export const INIT_STATE = 'INIT_DOCUMENT_STATE';
export const RESET_ERROR = 'RESET_DOCUMENT_ERROR';

export const RESET_DOWNLOAD_URL_LIST = 'RESET_DOWNLOAD_URL_LIST_DOCUMENT';
export const RESET_DELETE_URL = 'RESET_DELETE_URL_DOCUMENT';

// export const GET_DATA_LIST_LOADING = 'GET_DOCUMENT_LIST_LOADING';
// export const GET_DATA_LIST_SUCCESS = 'GET_DOCUMENT_LIST_SUCCESS';
// export const GET_DATA_LIST_ERROR = 'GET_DOCUMENT_LIST_ERROR';

// export const POST_DATA_LOADING = 'POST_DOCUMENT_LOADING';
// export const POST_DATA_SUCCESS = 'POST_DOCUMENT_SUCCESS';
// export const POST_DATA_ERROR = 'POST_DOCUMENT_ERROR';

// export const PUT_DATA_LOADING = 'PUT_DOCUMENT_LOADING';
// export const PUT_DATA_SUCCESS = 'PUT_DOCUMENT_SUCCESS';
// export const PUT_DATA_ERROR = 'PUT_DOCUMENT_ERROR';

export const DELETE_DATA_LOADING = 'DELETE_DOCUMENT_LOADING';
export const DELETE_DATA_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_DOCUMENT_ERROR';

// export const UPLOAD_FILE_LOADING = 'UPLOAD_DOCUMENT_FILE_LOADING';
// export const UPLOAD_FILE_SUCCESS = 'UPLOAD_DOCUMENT_FILE_SUCCESS';
// export const UPLOAD_FILE_ERROR = 'UPLOAD_DOCUMENT_FILE_ERROR';

// export const DELETE_FILE_LOADING = 'DELETE_DOCUMENT_FILE_LOADING';
// export const DELETE_FILE_SUCCESS = 'DELETE_DOCUMENT_FILE_SUCCESS';
// export const DELETE_FILE_ERROR = 'DELETE_DOCUMENT_FILE_ERROR';

export const UPLOAD_FILE_LOADING = 'UPLOAD_DOCUMENT_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_DOCUMENT_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_DOCUMENT_FILE_ERROR';

export const DELETE_FILE_LOADING = 'DELETE_DOCUMENT_FILE_LOADING';
export const DELETE_FILE_SUCCESS = 'DELETE_DOCUMENT_FILE_SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE_DOCUMENT_FILE_ERROR';

// export const POST_PUT_DATA_LOADING = 'POST_PUT_DOCUMENT_LOADING';
// export const POST_PUT_DATA_SUCCESS = 'POST_PUT_DOCUMENT_SUCCESS';
// export const POST_PUT_DATA_ERROR = 'POST_PUT_DOCUMENT_ERROR';

export const DOWNLOAD_FILE_LOADING = 'DOWNLOAD_DOCUMENT_FILE_LOADING';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_DOCUMENT_FILE_SUCCESS';
export const DOWNLOAD_FILE_ERROR = 'DOWNLOAD_DOCUMENT_FILE_ERROR';