export const INIT_STATE = 'INIT_PROFILE_STATE';

export const GET_DATA_LOADING = 'GET_PROFILE_LOADING';
export const GET_DATA_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_DATA_ERROR = 'GET_PROFILE_ERROR';

export const GET_ORGLOGO_LOADING = 'GET_ORGLOGO_LOADING';
export const GET_ORGLOGO_SUCCESS = 'GET_ORGLOGO_SUCCESS';
export const GET_ORGLOGO_ERROR = 'GET_ORGLOGO_ERROR';

export const GET_ALL_PLATFORM_SERVICES_LOADING = 'GET_ALL_PLATFORM_SERVICES_LOADING';
export const GET_ALL_PLATFORM_SERVICES_SUCCESS = 'GET_ALL_PLATFORM_SERVICES_SUCCESS';
export const GET_ALL_PLATFORM_SERVICES_ERROR = 'GET_ALL_PLATFORM_SERVICES_ERROR';

export const GET_ENABLED_PLATFORM_SERVICES_LOADING = 'GET_ENABLED_PLATFORM_SERVICES_LOADING';
export const GET_ENABLED_PLATFORM_SERVICES_SUCCESS = 'GET_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const GET_ENABLED_PLATFORM_SERVICES_ERROR = 'GET_ENABLED_PLATFORM_SERVICES_ERROR';

export const POST_ENABLED_PLATFORM_SERVICES_LOADING = 'POST_ENABLED_PLATFORM_SERVICES_LOADING';
export const POST_ENABLED_PLATFORM_SERVICES_SUCCESS = 'POST_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const POST_ENABLED_PLATFORM_SERVICES_ERROR = 'POST_ENABLED_PLATFORM_SERVICES_ERROR';

export const PUT_ENABLED_PLATFORM_SERVICES_LOADING = 'PUT_ENABLED_PLATFORM_SERVICES_LOADING';
export const PUT_ENABLED_PLATFORM_SERVICES_SUCCESS = 'PUT_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const PUT_ENABLED_PLATFORM_SERVICES_ERROR = 'PUT_ENABLED_PLATFORM_SERVICES_ERROR';

export const DELETE_BGV_CONFIG_LOADING = 'DELETE_BGV_CONFIG_LOADING';
export const DELETE_BGV_CONFIG_SUCCESS = 'DELETE_BGV_CONFIG_SUCCESS';
export const DELETE_BGV_CONFIG_ERROR = 'DELETE_BGV_CONFIG_ERROR';

export const DELETE_OPS_CONFIG_LOADING = 'DELETE_OPS_CONFIG_LOADING';
export const DELETE_OPS_CONFIG_SUCCESS = 'DELETE_OPS_CONFIG_SUCCESS';
export const DELETE_OPS_CONFIG_ERROR = 'DELETE_OPS_CONFIG_ERROR';

export const GET_OPS_SELECTED_SERVICE_DATA_LOADING = 'GET_OPS_SELECTED_SERVICE_DATA_LOADING';
export const GET_OPS_SELECTED_SERVICE_DATA_SUCCESS = 'GET_OPS_SELECTED_SERVICE_DATA_SUCCESS';
export const GET_OPS_SELECTED_SERVICE_DATA_ERROR = 'GET_OPS_SELECTED_SERVICE_DATA_ERROR';

export const GET_BGV_SELECTED_SERVICE_DATA_LOADING = 'GET_BGV_SELECTED_SERVICE_DATA_LOADING';
export const GET_BGV_SELECTED_SERVICE_DATA_SUCCESS = 'GET_BGV_SELECTED_SERVICE_DATA_SUCCESS';
export const GET_BGV_SELECTED_SERVICE_DATA_ERROR = 'GET_BGV_SELECTED_SERVICE_DATA_ERROR';

export const GET_CLIENT_NOTIFICATION_LOADING = 'GET_CLIENT_NOTIFICATION_LOADING';
export const GET_CLIENT_NOTIFICATION_SUCCESS = 'GET_CLIENT_NOTIFICATION_SUCCESS';
export const GET_CLIENT_NOTIFICATION_ERROR = 'GET_CLIENT_NOTIFICATION_ERROR';