export const INIT_STATE = 'INIT_DETAILS_STATE';
export const RESET_ERROR = 'RESET_DETAILS_ERROR';

export const POST_DATA_LOADING = 'POST_DETAILS_LOADING';
export const POST_DATA_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DATA_ERROR = 'POST_DETAILS_ERROR';

export const PUT_DATA_LOADING = 'PUT_DETAILS_LOADING';
export const PUT_DATA_SUCCESS = 'PUT_DETAILS_SUCCESS';
export const PUT_DATA_ERROR = 'PUT_DETAILS_ERROR';

export const GET_DATA_LOADING = 'GET_DETAILS_LOADING';
export const GET_DATA_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DATA_ERROR = 'GET_DETAILS_ERROR';

export const DELETE_DATA_LOADING = 'DELETE_DETAILS_LOADING';
export const DELETE_DATA_SUCCESS = 'DELETE_DETAILS_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_DETAILS_ERROR';

export const GET_ORGLOGO_LOADING='GET_ORGLOGO_LOADING';
export const GET_ORGLOGO_SUCCESS='GET_ORGLOGO_SUCCESS';
export const GET_ORGLOGO_ERROR='GET_ORGLOGO_ERROR';