export const INIT_STATE = 'INIT_ORG_LIST_STATE';

export const GET_CLIENT_LIST_LOADING = 'GET_DEPLOY_CLIENT_LIST_LOADING';
export const GET_CLIENT_LIST_SUCCESS = 'GET_DEPLOY_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_ERROR = 'GET_DEPLOY_CLIENT_LIST_ERROR';

export const POST_DEPLOY_EMP_LOADING = 'POST_DEPLOY_EMP_LOADING';
export const POST_DEPLOY_EMP_SUCCESS = 'POST_DEPLOY_EMP_SUCCESS';
export const POST_DEPLOY_EMP_ERROR = 'POST_DEPLOY_EMP_ERROR';


