export const INIT_CONFIG_TAG_MAP_LIST = 'INIT_CONFIG_TAG_MAP_LIST';

export const GET_CONFIG_TAG_MAP_LIST_LOADING = 'GET_CONFIG_TAG_MAP_LIST_LOADING';
export const GET_CONFIG_TAG_MAP_LIST_SUCCESS = 'GET_CONFIG_TAG_MAP_LIST_SUCCESS';
export const GET_CONFIG_TAG_MAP_LIST_ERROR = 'GET_CONFIG_TAG_MAP_LIST_ERROR';

export const POST_CONFIG_TAG_MAP_LIST_LOADING = 'POST_CONFIG_TAG_MAP_LIST_LOADING';
export const POST_CONFIG_TAG_MAP_LIST_SUCCESS = 'POST_CONFIG_TAG_MAP_LIST_SUCCESS';
export const POST_CONFIG_TAG_MAP_LIST_ERROR = 'POST_CONFIG_TAG_MAP_LIST_ERROR';

export const PUT_CONFIG_TAG_MAP_LIST_LOADING = 'PUT_CONFIG_TAG_MAP_LIST_LOADING';
export const PUT_CONFIG_TAG_MAP_LIST_SUCCESS = 'PUT_CONFIG_TAG_MAP_LIST_SUCCESS';
export const PUT_CONFIG_TAG_MAP_LIST_ERROR = 'PUT_CONFIG_TAG_MAP_LIST_ERROR';

export const POST_TAG_INFO_DATA_LOADING = 'POST_TAG_INFO_DATA_LOADING';
export const POST_TAG_INFO_DATA_SUCCESS = 'POST_TAG_INFO_DATA_SUCCESS';
export const POST_TAG_INFO_DATA_ERROR = 'POST_TAG_INFO_DATA_ERROR';

export const GET_ENABLED_PLATFORM_SERVICES_LOADING='GET_ENABLED_PLATFORM_SERVICES_LOADING';
export const GET_ENABLED_PLATFORM_SERVICES_SUCCESS='GET_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const GET_ENABLED_PLATFORM_SERVICES_ERROR='GET_ENABLED_PLATFORM_SERVICES_ERROR';

export const POST_ENABLED_PLATFORM_SERVICES_LOADING='POST_ENABLED_PLATFORM_SERVICES_LOADING';
export const POST_ENABLED_PLATFORM_SERVICES_SUCCESS='POST_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const POST_ENABLED_PLATFORM_SERVICES_ERROR='POST_ENABLED_PLATFORM_SERVICES_ERROR';

export const PUT_ENABLED_PLATFORM_SERVICES_LOADING='PUT_ENABLED_PLATFORM_SERVICES_LOADING';
export const PUT_ENABLED_PLATFORM_SERVICES_SUCCESS='PUT_ENABLED_PLATFORM_SERVICES_SUCCESS';
export const PUT_ENABLED_PLATFORM_SERVICES_ERROR='PUT_ENABLED_PLATFORM_SERVICES_ERROR';
