export const POST_ORG_ATTENDANCE_CONFIG_LOADING = 'POST_ORG_ATTENDANCE_CONFIG_LOADING';
export const POST_ORG_ATTENDANCE_CONFIG_SUCCESS = 'POST_ORG_ATTENDANCE_CONFIG_SUCCESS';
export const POST_ORG_ATTENDANCE_CONFIG_ERROR = 'POST_ORG_ATTENDANCE_CONFIG_ERROR';

export const GET_ORG_ATTENDANCE_CONFIG_LOADING = 'GET_ORG_ATTENDANCE_CONFIG_LOADING';
export const GET_ORG_ATTENDANCE_CONFIG_SUCCESS = 'GET_ORG_ATTENDANCE_CONFIG_SUCCESS';
export const GET_ORG_ATTENDANCE_CONFIG_ERROR = 'GET_ORG_ATTENDANCE_CONFIG_ERROR';
export const ORG_ATTD_CONFIG_HISTORY = 'ORG_ATTD_CONFIG_HISTORY';
export const ORG_ATTD_CONFIG_HISTORY_ERR = 'ORG_ATTD_CONFIG_HISTORY_ERR';
export const ORG_HISTORY_EDITED_BY = 'ORG_HISTORY_EDITED_BY';
export const ORG_HISTORY_EDITED_BY_ERR = 'ORG_HISTORY_EDITED_BY_ERR';
