export const INIT_STATE = 'INIT_RESET_STATE';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_LOADING = 'GET_USER_PROFILE_LOADING';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';